_base_ = ['./base_e2e_lidar_llm_probe.py']

# Stage-1 hard-GT QA probe: same frozen LiDAR query setup as the caption probe,
# but train the LLM bridge to answer deterministic geometry/trajectory QA pairs
# generated by tools/data_converter/gen_vlm_qa.py. This is a cleaner first
# target than free-form VLM summaries because every answer is traceable to
# geo_facts / 3D boxes / future trajectories / rules.

model = dict(
    llm_head=dict(
        training_mode='qa',
        qa_prompt_template='请基于本车周围的激光雷达目标回答问题：{question}',
        qa_index_strategy='hash',
        # Keep the first QA probe focused on hard safety/geometry facts.
        # activity_gate is included as a gating fact, not a visual working/idle
        # label; visual-state answers should come from a later teacher pass.
        qa_answer_types=[
            'summary', 'risk', 'advice', 'activity_gate',
            'spatial', 'motion', 'count',
        ],
        max_text_len=160))

data = dict(
    train=dict(ann_file='kl_infos_train_vlmqa.pkl'),
    val=dict(ann_file='kl_infos_val_sub6cam_v3_vlmqa.pkl'),
    test=dict(ann_file='kl_infos_val_sub6cam_v3_vlmqa.pkl'))

work_dir = './projects/work_dirs/stage2_e2e_lidar/base_e2e_lidar_llm_qa_probe'
