"""Visualize KL LiDAR detection results with BEV velocity arrows.

Examples:
    python tools/visualize_kl_velocity.py \
        --config projects/configs/bevformer_lidar/base_bevformer_lidar.py \
        --results-pkl output/results.pkl \
        --out-dir work_dirs/vis_base_bevformer_lidar_velocity \
        --max-frames 20 --score-thr 0.2 --annotate

    python tools/visualize_kl_velocity.py \
        --config projects/configs/bevformer_lidar/base_bevformer_lidar.py \
        --results-json work_dirs/.../results_nusc.json \
        --out-dir work_dirs/vis_base_bevformer_lidar_velocity
"""

from __future__ import annotations

import argparse
import json
import math
import os
import os.path as osp
import subprocess
from typing import Dict, List, Optional, Sequence

os.environ.setdefault('MPLCONFIGDIR', '/tmp/matplotlib')

import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import mmcv
import numpy as np
import torch
from mmcv import Config


KL_CLASSES = (
    'Pedestrian', 'Car', 'IGV-Full', 'Truck', 'Trailer-Empty',
    'Trailer-Full', 'IGV-Empty', 'Crane', 'OtherVehicle', 'Cone',
    'ContainerForklift', 'Forklift', 'Lorry', 'ConstructionVehicle',
    'WheelCrane',
)


def parse_args():
    parser = argparse.ArgumentParser(
        description='Visualize KL detections with velocity arrows.')
    parser.add_argument('--config', required=True, help='UniAD config path')
    parser.add_argument(
        '--results-pkl',
        help='UniAD results.pkl from tools/test.py or dist eval')
    parser.add_argument(
        '--results-json',
        help='results_nusc.json generated by KL dataset formatting')
    parser.add_argument('--out-dir', required=True, help='output image dir')
    parser.add_argument(
        '--split',
        default='val',
        choices=['val', 'test'],
        help='which config data split to visualize')
    parser.add_argument('--score-thr', type=float, default=0.2)
    parser.add_argument(
        '--max-frames',
        type=int,
        default=20,
        help='0 means all selected frames')
    parser.add_argument(
        '--indices',
        type=int,
        nargs='*',
        default=None,
        help='explicit dataset indices to render')
    parser.add_argument(
        '--tokens',
        nargs='*',
        default=None,
        help='explicit sample tokens to render')
    parser.add_argument('--topk', type=int, default=80)
    parser.add_argument(
        '--point-stride',
        type=int,
        default=4,
        help='subsample point cloud for rendering')
    parser.add_argument(
        '--vel-scale',
        type=float,
        default=3.0,
        help='meters drawn per m/s of velocity')
    parser.add_argument('--min-vel-draw', type=float, default=0.2)
    parser.add_argument('--annotate', action='store_true')
    parser.add_argument('--skip-existing', action='store_true')
    parser.add_argument(
        '--webm-fps',
        type=float,
        default=3.0,
        help='FPS for velocity_vis.webm. Set <= 0 to skip WebM.')
    parser.add_argument(
        '--webm-crf',
        type=int,
        default=34,
        help='VP9 CRF for velocity_vis.webm; lower is higher quality.')
    args = parser.parse_args()

    if bool(args.results_pkl) == bool(args.results_json):
        raise ValueError('Specify exactly one of --results-pkl/--results-json')
    if args.point_stride <= 0:
        raise ValueError('--point-stride must be > 0')
    if args.topk <= 0:
        raise ValueError('--topk must be > 0')
    return args


def get_dataset_cfg(cfg: Config, split: str):
    data = cfg.data
    return data.val if split == 'val' else data.test


def get_class_names(cfg: Config, dataset_cfg) -> Sequence[str]:
    if dataset_cfg.get('classes', None) is not None:
        return list(dataset_cfg.classes)
    if cfg.get('class_names', None) is not None:
        return list(cfg.class_names)
    return list(KL_CLASSES)


def get_label_mapping(cfg: Config, dataset_cfg) -> Optional[List[int]]:
    mapping = dataset_cfg.get('label_mapping', None)
    if mapping is None:
        mapping = cfg.get('label_mapping', None)
    if mapping is None:
        return None
    return [int(x) for x in mapping]


def resolve_info_path(cfg: Config, dataset_cfg) -> str:
    data_root = dataset_cfg.get('data_root', cfg.get('data_root', ''))
    ann_file = dataset_cfg.ann_file
    if osp.isabs(ann_file):
        return ann_file
    return osp.join(data_root, ann_file)


def load_info_list(info_path: str) -> List[dict]:
    data = mmcv.load(info_path)
    if isinstance(data, dict):
        if 'data_list' in data:
            return data['data_list']
        if 'infos' in data:
            return data['infos']
    if isinstance(data, list):
        return data
    raise TypeError(f'Unsupported info file structure: {info_path}')


def collect_queue_indices(info_list: List[dict], token2index: Dict[str, int],
                          raw_index: int, queue_length: int,
                          max_time_gap: float) -> Optional[List[int]]:
    if queue_length <= 1:
        return [raw_index]

    current = info_list[raw_index]
    scene_token = current.get('scene_token')
    indices = [raw_index]
    cursor = current
    prev_token = current.get('prev', '')
    for _ in range(queue_length - 1):
        if not prev_token:
            return None
        prev_index = token2index.get(prev_token)
        if prev_index is None:
            return None
        prev_info = info_list[prev_index]
        if prev_info.get('scene_token') != scene_token:
            return None
        dt = abs(float(cursor.get('timestamp', 0.0)) -
                 float(prev_info.get('timestamp', 0.0)))
        if dt > max_time_gap:
            return None
        indices.append(prev_index)
        cursor = prev_info
        prev_token = prev_info.get('prev', '')

    indices.reverse()
    return indices


def filter_infos_like_dataset(info_list: List[dict], dataset_cfg):
    dataset_type = dataset_cfg.get('type', '')
    queue_length = int(dataset_cfg.get('queue_length', 1))
    max_time_gap = float(dataset_cfg.get('max_time_gap', 1.0))
    if dataset_type != 'KlBEVFormerDataset' or queue_length <= 1:
        return info_list, list(range(len(info_list)))

    token2index = {
        info.get('token'): idx
        for idx, info in enumerate(info_list)
        if info.get('token')
    }
    valid_raw_indices = [
        idx for idx in range(len(info_list))
        if collect_queue_indices(info_list, token2index, idx, queue_length,
                                 max_time_gap) is not None
    ]
    filtered_infos = [info_list[idx] for idx in valid_raw_indices]
    return filtered_infos, valid_raw_indices


def resolve_lidar_path(cfg: Config, dataset_cfg, info: dict) -> str:
    data_root = dataset_cfg.get('data_root', cfg.get('data_root', ''))
    data_prefix = dataset_cfg.get('data_prefix', cfg.get('data_prefix', {}))
    pts_prefix = data_prefix.get('pts', '')
    lidar_info = info.get('lidar_points', {})
    lidar_path = lidar_info.get('lidar_path', info.get('lidar_path'))
    if lidar_path is None:
        raise KeyError('info does not contain lidar path')
    if osp.isabs(lidar_path) or osp.exists(lidar_path):
        return lidar_path
    return osp.join(data_root, pts_prefix, lidar_path)


def load_points(cfg: Config, dataset_cfg, info: dict) -> np.ndarray:
    lidar_path = resolve_lidar_path(cfg, dataset_cfg, info)
    lidar_info = info.get('lidar_points', {})
    num_feats = int(lidar_info.get('num_pts_feats',
                                   info.get('num_features', 4)))
    points = np.fromfile(lidar_path, dtype=np.float32)
    return points.reshape(-1, num_feats)


def map_label(label: int, label_mapping: Optional[List[int]],
              num_classes: int) -> int:
    label = int(label)
    if label_mapping is not None:
        if label < 0 or label >= len(label_mapping):
            return -1
        label = int(label_mapping[label])
    if label < 0 or label >= num_classes:
        return -1
    return label


def gt_arrays_from_info(info: dict, dataset_cfg, class_names: Sequence[str],
                        label_mapping: Optional[List[int]]) -> Dict[str, np.ndarray]:
    use_valid_flag = bool(dataset_cfg.get('use_valid_flag', False))
    instances = info.get('instances', [])
    boxes = []
    labels = []

    if instances:
        for inst in instances:
            raw_label = inst.get('bbox_label_3d', inst.get('bbox_label', -1))
            label = map_label(raw_label, label_mapping, len(class_names))
            if label < 0:
                continue
            valid = bool(inst.get('bbox_3d_isvalid', True)) if use_valid_flag \
                else int(inst.get('num_lidar_pts', 1)) > 0
            if not valid:
                continue
            box = np.asarray(inst['bbox_3d'], dtype=np.float32)
            vel = np.asarray(inst.get('velocity', [0.0, 0.0]),
                             dtype=np.float32)
            if box.shape[0] == 7:
                box = np.concatenate([box, vel[:2]], axis=0)
            elif box.shape[0] >= 9:
                box = box.copy()
                box[7:9] = vel[:2]
            if box.shape[0] < 9:
                box = np.pad(box, (0, 9 - box.shape[0]))
            boxes.append(box[:9])
            labels.append(label)
    elif 'gt_boxes' in info:
        gt_boxes = np.asarray(info['gt_boxes'], dtype=np.float32)
        gt_names = info.get('gt_names', [])
        valid_flags = info.get('valid_flag', [True] * len(gt_boxes))
        name_to_label = {name: idx for idx, name in enumerate(class_names)}
        for box, name, valid in zip(gt_boxes, gt_names, valid_flags):
            if use_valid_flag and not valid:
                continue
            label = name_to_label.get(str(name), -1)
            if label < 0:
                continue
            if box.shape[0] < 9:
                box = np.pad(box, (0, 9 - box.shape[0]))
            boxes.append(box[:9])
            labels.append(label)

    if not boxes:
        return empty_arrays()
    return dict(
        boxes=np.asarray(boxes, dtype=np.float32),
        labels=np.asarray(labels, dtype=np.int64),
        scores=np.ones((len(boxes),), dtype=np.float32))


def empty_arrays() -> Dict[str, np.ndarray]:
    return dict(
        boxes=np.zeros((0, 9), dtype=np.float32),
        labels=np.zeros((0,), dtype=np.int64),
        scores=np.zeros((0,), dtype=np.float32))


def tensor_to_numpy(value) -> np.ndarray:
    if isinstance(value, torch.Tensor):
        return value.detach().cpu().numpy()
    return np.asarray(value)


def boxes_to_numpy(boxes_3d) -> np.ndarray:
    if boxes_3d is None:
        return np.zeros((0, 9), dtype=np.float32)
    if hasattr(boxes_3d, 'tensor'):
        boxes = boxes_3d.tensor.detach().cpu().numpy()
    else:
        boxes = tensor_to_numpy(boxes_3d)
    boxes = boxes.astype(np.float32)
    if boxes.ndim == 1:
        boxes = boxes.reshape(1, -1)
    if boxes.shape[1] < 9:
        pad = np.zeros((boxes.shape[0], 9 - boxes.shape[1]), dtype=boxes.dtype)
        boxes = np.concatenate([boxes, pad], axis=1)
    return boxes[:, :9]


def unwrap_pkl_result(result):
    if isinstance(result, dict) and 'pts_bbox' in result:
        return result['pts_bbox']
    return result


def pred_arrays_from_pkl_result(result, score_thr: float,
                                topk: int) -> Dict[str, np.ndarray]:
    result = unwrap_pkl_result(result)
    if not isinstance(result, dict):
        return empty_arrays()
    boxes = boxes_to_numpy(result.get('boxes_3d'))
    scores = tensor_to_numpy(result.get('scores_3d', np.zeros((len(boxes),))))
    labels = tensor_to_numpy(result.get('labels_3d', np.zeros((len(boxes),))))
    scores = scores.astype(np.float32).reshape(-1)
    labels = labels.astype(np.int64).reshape(-1)
    if len(boxes) == 0:
        return empty_arrays()
    order = np.argsort(-scores)
    keep = order[scores[order] >= score_thr][:topk]
    return dict(boxes=boxes[keep], labels=labels[keep], scores=scores[keep])


def quat_to_yaw(quat: Sequence[float]) -> float:
    w, x, y, z = [float(v) for v in quat]
    siny_cosp = 2.0 * (w * z + x * y)
    cosy_cosp = 1.0 - 2.0 * (y * y + z * z)
    return math.atan2(siny_cosp, cosy_cosp)


def pred_arrays_from_json(entries: List[dict], class_names: Sequence[str],
                          score_thr: float, topk: int) -> Dict[str, np.ndarray]:
    name_to_label = {name: idx for idx, name in enumerate(class_names)}
    kept = [
        item for item in entries
        if float(item.get('detection_score', 0.0)) >= score_thr
        and item.get('detection_name') in name_to_label
    ]
    kept.sort(key=lambda item: float(item.get('detection_score', 0.0)),
              reverse=True)
    kept = kept[:topk]
    if not kept:
        return empty_arrays()

    boxes = []
    labels = []
    scores = []
    for item in kept:
        x, y, z = item['translation']
        w, l, h = item['size']
        yaw = quat_to_yaw(item['rotation'])
        vx, vy = item.get('velocity', [0.0, 0.0])
        boxes.append([x, y, z, l, w, h, yaw, vx, vy])
        labels.append(name_to_label[item['detection_name']])
        scores.append(float(item['detection_score']))
    return dict(
        boxes=np.asarray(boxes, dtype=np.float32),
        labels=np.asarray(labels, dtype=np.int64),
        scores=np.asarray(scores, dtype=np.float32))


def load_results_pkl(path: str) -> List[dict]:
    loaded = mmcv.load(path)
    if isinstance(loaded, dict) and 'bbox_results' in loaded:
        loaded = loaded['bbox_results']
    if not isinstance(loaded, list):
        raise TypeError(f'Unsupported pkl result structure: {type(loaded)}')
    return loaded


def sample_indices(total: int, max_frames: int,
                   indices: Optional[Sequence[int]]) -> List[int]:
    if indices:
        out = []
        for idx in indices:
            if idx < 0 or idx >= total:
                raise IndexError(f'Index {idx} out of range 0..{total - 1}')
            out.append(int(idx))
        return out
    if max_frames == 0 or max_frames >= total:
        return list(range(total))
    return list(range(max_frames))


def compute_box_corners_bev(boxes: np.ndarray) -> np.ndarray:
    if boxes.size == 0:
        return np.zeros((0, 4, 2), dtype=np.float32)
    corners = []
    for box in boxes:
        x, y, _, l, w, _, yaw = box[:7]
        c = math.cos(float(yaw))
        s = math.sin(float(yaw))
        rot = np.array([[c, -s], [s, c]], dtype=np.float32)
        local = np.array([
            [l / 2, w / 2],
            [l / 2, -w / 2],
            [-l / 2, -w / 2],
            [-l / 2, w / 2],
        ], dtype=np.float32)
        corners.append(local @ rot.T + np.array([x, y], dtype=np.float32))
    return np.stack(corners, axis=0)


def lidar_xy_to_display(xy: np.ndarray) -> np.ndarray:
    disp = np.empty_like(xy, dtype=np.float32)
    disp[..., 0] = -xy[..., 1]
    disp[..., 1] = xy[..., 0]
    return disp


def draw_boxes(ax, boxes: np.ndarray, labels: np.ndarray,
               scores: Optional[np.ndarray], class_names: Sequence[str],
               color: str, vel_scale: float, min_vel_draw: float,
               annotate: bool = False, alpha: float = 1.0) -> None:
    if boxes.size == 0:
        return

    corners = compute_box_corners_bev(boxes)
    for idx, box in enumerate(boxes):
        poly = corners[idx]
        poly_disp = lidar_xy_to_display(poly)
        closed_disp = np.concatenate([poly_disp, poly_disp[:1]], axis=0)
        ax.plot(closed_disp[:, 0], closed_disp[:, 1],
                color=color, linewidth=1.4, alpha=alpha)

        center_xy_disp = lidar_xy_to_display(
            np.array([[box[0], box[1]]], dtype=np.float32))[0]
        center_x = float(center_xy_disp[0])
        center_y = float(center_xy_disp[1])

        yaw = float(box[6])
        heading_len = min(max(float(box[3]) * 0.22, 0.45), 1.35)
        heading_vec_lidar = np.array(
            [[math.cos(yaw), math.sin(yaw)]], dtype=np.float32)
        heading_vec_disp = lidar_xy_to_display(heading_vec_lidar)[0]
        ax.plot(
            [center_x, center_x + float(heading_vec_disp[0]) * heading_len],
            [center_y, center_y + float(heading_vec_disp[1]) * heading_len],
            color=color, linewidth=0.9, linestyle='--', alpha=0.6)

        vx, vy = float(box[7]), float(box[8])
        speed = math.hypot(vx, vy)
        if speed >= min_vel_draw:
            vel_disp = lidar_xy_to_display(
                np.array([[vx, vy]], dtype=np.float32))[0]
            dx = float(vel_disp[0]) * vel_scale
            dy = float(vel_disp[1]) * vel_scale
            disp_len = math.hypot(dx, dy)
            ax.arrow(
                center_x, center_y, dx, dy,
                color=color,
                width=min(max(disp_len * 0.012, 0.015), 0.05),
                head_width=min(max(disp_len * 0.14, 0.12), 0.6),
                head_length=min(max(disp_len * 0.22, 0.18), 0.9),
                length_includes_head=True,
                alpha=alpha)

        if annotate:
            label = int(labels[idx])
            label_name = class_names[label] if 0 <= label < len(class_names) \
                else str(label)
            score_text = '' if scores is None else f' {float(scores[idx]):.2f}'
            ax.text(center_x, center_y,
                    f'{label_name}{score_text} {speed:.2f}m/s',
                    color=color, fontsize=6, ha='left', va='bottom',
                    alpha=alpha)


def render_frame(points: np.ndarray, gt_data: Dict[str, np.ndarray],
                 pred_data: Dict[str, np.ndarray], class_names: Sequence[str],
                 save_path: str, title_id: str, pc_range: Sequence[float],
                 vel_scale: float, min_vel_draw: float, point_stride: int,
                 annotate: bool) -> None:
    x_min, y_min, _, x_max, y_max, _ = [float(v) for v in pc_range]
    disp_x_min, disp_x_max = -y_max, -y_min
    disp_y_min, disp_y_max = x_min, x_max

    fig, ax = plt.subplots(figsize=(12, 8), dpi=160)
    fig.patch.set_facecolor('black')
    ax.set_facecolor('black')

    pts = points[::point_stride, :3]
    if len(pts):
        pts_disp = lidar_xy_to_display(pts[:, :2])
        ax.scatter(pts_disp[:, 0], pts_disp[:, 1], s=0.12, c='white',
                   alpha=0.35, linewidths=0)

    draw_boxes(ax, gt_data['boxes'], gt_data['labels'], None, class_names,
               color='#00ff88', vel_scale=vel_scale,
               min_vel_draw=min_vel_draw, annotate=False, alpha=0.95)
    draw_boxes(ax, pred_data['boxes'], pred_data['labels'],
               pred_data['scores'], class_names, color='#ff4d4d',
               vel_scale=vel_scale, min_vel_draw=min_vel_draw,
               annotate=annotate, alpha=0.95)

    ax.plot(0.0, 0.0, marker='o', markersize=4, color='#ffd166')
    ax.arrow(0.0, 0.0, 0.0, 3.0, color='#ffd166', width=0.03,
             head_width=0.5, head_length=0.6, length_includes_head=True)

    ax.set_xlim(disp_x_min, disp_x_max)
    ax.set_ylim(disp_y_min, disp_y_max)
    ax.set_aspect('equal', adjustable='box')
    ax.set_xlabel('Lateral (m)', color='white')
    ax.set_ylabel('Forward (m)', color='white')
    ax.tick_params(colors='white', labelsize=8)
    for spine in ax.spines.values():
        spine.set_color('#888888')
    ax.grid(color='#444444', linestyle='--', linewidth=0.5, alpha=0.4)

    gt_speed = np.linalg.norm(gt_data['boxes'][:, 7:9], axis=1) \
        if len(gt_data['boxes']) else np.zeros((0,), dtype=np.float32)
    pred_speed = np.linalg.norm(pred_data['boxes'][:, 7:9], axis=1) \
        if len(pred_data['boxes']) else np.zeros((0,), dtype=np.float32)
    ax.set_title(
        f'KL BEV velocity | {title_id}\n'
        f'GT={len(gt_data["boxes"])} mean_speed={gt_speed.mean():.2f} m/s | '
        f'Pred={len(pred_data["boxes"])} '
        f'mean_speed={pred_speed.mean():.2f} m/s',
        color='white',
        fontsize=10)

    legend_lines = [
        plt.Line2D([0], [0], color='#00ff88', lw=2),
        plt.Line2D([0], [0], color='#ff4d4d', lw=2),
        plt.Line2D([0], [0], color='#ffd166', lw=2),
    ]
    ax.legend(legend_lines,
              ['GT boxes + velocity', 'Pred boxes + velocity', 'Ego heading'],
              loc='upper right', facecolor='black', edgecolor='#888888',
              labelcolor='white', fontsize=8)

    fig.tight_layout()
    fig.savefig(save_path, facecolor=fig.get_facecolor(), bbox_inches='tight')
    plt.close(fig)


def safe_token(token: str) -> str:
    return str(token).replace('/', '_').replace('\\', '_')


def selected_indices(info_list: List[dict], args) -> List[int]:
    if args.tokens:
        token_to_idx = {
            str(info.get('token', idx)): idx for idx, info in enumerate(info_list)
        }
        missing = [token for token in args.tokens if token not in token_to_idx]
        if missing:
            raise KeyError(f'Tokens not found in infos: {missing}')
        return [token_to_idx[token] for token in args.tokens]
    return sample_indices(len(info_list), args.max_frames, args.indices)


def write_html_player(out_dir: str, frame_files: List[str]) -> None:
    frames = [osp.basename(path) for path in frame_files]
    if not frames:
        return
    frame_items = ',\n      '.join(f'"{name}"' for name in frames)
    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>KL Velocity Sequence</title>
  <style>
    body {{
      margin: 0;
      background: #101114;
      color: #f2f5fa;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    main {{
      width: min(1500px, calc(100vw - 32px));
      margin: 0 auto;
      padding: 18px 0 28px;
    }}
    header {{
      display: flex;
      justify-content: space-between;
      align-items: baseline;
      gap: 16px;
      margin-bottom: 12px;
    }}
    h1 {{ margin: 0; font-size: 18px; letter-spacing: 0; }}
    #frameText {{ color: #9aa4b2; font-size: 13px; white-space: nowrap; }}
    .stage {{
      display: grid;
      place-items: center;
      min-height: 360px;
      background: #050608;
      border: 1px solid #343844;
      border-radius: 6px;
      overflow: hidden;
    }}
    #frameImage {{
      display: block;
      max-width: 100%;
      max-height: calc(100vh - 210px);
      width: auto;
      height: auto;
    }}
    .controls {{
      display: grid;
      gap: 10px;
      margin-top: 12px;
      padding: 12px;
      background: #181a20;
      border: 1px solid #343844;
      border-radius: 6px;
    }}
    .row {{ display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }}
    button {{
      height: 34px;
      min-width: 42px;
      padding: 0 12px;
      border: 1px solid #343844;
      border-radius: 5px;
      background: #222631;
      color: #f2f5fa;
      font: inherit;
      cursor: pointer;
    }}
    button.primary {{ background: #113548; border-color: #26637d; }}
    input[type="range"] {{
      flex: 1 1 300px;
      min-width: 160px;
      accent-color: #64d2ff;
    }}
    input[type="number"] {{
      width: 72px;
      height: 32px;
      border: 1px solid #343844;
      border-radius: 5px;
      background: #11141a;
      color: #f2f5fa;
      padding: 0 8px;
      font: inherit;
    }}
    label {{
      display: inline-flex;
      align-items: center;
      gap: 6px;
      color: #9aa4b2;
      font-size: 13px;
    }}
  </style>
</head>
<body>
  <main>
    <header>
      <h1>KL Velocity Sequence</h1>
      <div id="frameText"></div>
    </header>
    <section class="stage">
      <img id="frameImage" alt="velocity frame">
    </section>
    <section class="controls">
      <div class="row">
        <button id="prevBtn">Prev</button>
        <button id="playBtn" class="primary">Play</button>
        <button id="nextBtn">Next</button>
        <label>FPS <input id="fpsInput" type="number" value="3" min="0.5" max="30" step="0.5"></label>
        <label><input id="loopInput" type="checkbox" checked> Loop</label>
      </div>
      <div class="row">
        <input id="frameSlider" type="range" min="0" max="{len(frames) - 1}" value="0" step="1">
      </div>
    </section>
  </main>
  <script>
    const frames = [
      {frame_items}
    ];
    const image = document.getElementById("frameImage");
    const text = document.getElementById("frameText");
    const slider = document.getElementById("frameSlider");
    const playBtn = document.getElementById("playBtn");
    const fpsInput = document.getElementById("fpsInput");
    const loopInput = document.getElementById("loopInput");
    let index = 0;
    let timer = null;
    function setFrame(nextIndex) {{
      index = Math.max(0, Math.min(frames.length - 1, nextIndex));
      image.src = frames[index];
      slider.value = index;
      text.textContent = `Frame ${{index + 1}} / ${{frames.length}} | ${{frames[index]}}`;
    }}
    function stop() {{
      if (timer !== null) {{
        clearInterval(timer);
        timer = null;
      }}
      playBtn.textContent = "Play";
    }}
    function play() {{
      stop();
      playBtn.textContent = "Pause";
      const fps = Math.max(0.5, Number(fpsInput.value) || 3);
      timer = setInterval(() => {{
        if (index >= frames.length - 1) {{
          if (!loopInput.checked) {{
            stop();
            return;
          }}
          setFrame(0);
          return;
        }}
        setFrame(index + 1);
      }}, 1000 / fps);
    }}
    function togglePlay() {{ timer === null ? play() : stop(); }}
    document.getElementById("prevBtn").addEventListener("click", () => {{ stop(); setFrame(index - 1); }});
    document.getElementById("nextBtn").addEventListener("click", () => {{ stop(); setFrame(index + 1); }});
    playBtn.addEventListener("click", togglePlay);
    fpsInput.addEventListener("change", () => {{ if (timer !== null) play(); }});
    slider.addEventListener("input", () => {{ stop(); setFrame(Number(slider.value)); }});
    document.addEventListener("keydown", (event) => {{
      if (event.key === " ") {{ event.preventDefault(); togglePlay(); }}
      else if (event.key === "ArrowLeft") {{ stop(); setFrame(index - 1); }}
      else if (event.key === "ArrowRight") {{ stop(); setFrame(index + 1); }}
    }});
    setFrame(0);
  </script>
</body>
</html>
"""
    with open(osp.join(out_dir, 'index.html'), 'w', encoding='utf-8') as f:
        f.write(html)


def write_webm_video(out_dir: str, fps: float = 3.0,
                     crf: int = 34) -> None:
    if fps <= 0:
        return
    output_path = osp.join(out_dir, 'velocity_vis.webm')
    input_glob = osp.join(out_dir, '*.png')
    cmd = [
        'ffmpeg',
        '-y',
        '-framerate',
        str(float(fps)),
        '-pattern_type',
        'glob',
        '-i',
        input_glob,
        '-vf',
        'pad=ceil(iw/2)*2:ceil(ih/2)*2',
        '-c:v',
        'libvpx-vp9',
        '-b:v',
        '0',
        '-crf',
        str(int(crf)),
        output_path,
    ]
    try:
        subprocess.run(cmd, check=True)
    except FileNotFoundError:
        print('[WARN] ffmpeg not found; skipped WebM generation.')
    except subprocess.CalledProcessError as exc:
        print(f'[WARN] ffmpeg failed with exit code {exc.returncode}; '
              'skipped WebM generation.')


def main():
    args = parse_args()
    cfg = Config.fromfile(args.config)
    dataset_cfg = get_dataset_cfg(cfg, args.split)
    class_names = get_class_names(cfg, dataset_cfg)
    label_mapping = get_label_mapping(cfg, dataset_cfg)
    raw_info_list = load_info_list(resolve_info_path(cfg, dataset_cfg))
    info_list, raw_indices = filter_infos_like_dataset(raw_info_list,
                                                       dataset_cfg)
    if len(info_list) != len(raw_info_list):
        print(f'[INFO] dataset queue filter kept {len(info_list)}/'
              f'{len(raw_info_list)} infos')
    indices = selected_indices(info_list, args)

    pkl_results = None
    json_results = None
    if args.results_pkl:
        pkl_results = load_results_pkl(args.results_pkl)
        if len(pkl_results) != len(info_list):
            print(f'[WARN] results length {len(pkl_results)} != '
                  f'dataset info length {len(info_list)}')
    else:
        with open(args.results_json, 'r') as f:
            payload = json.load(f)
        json_results = payload['results']

    mmcv.mkdir_or_exist(args.out_dir)
    summary = []
    frame_files = []
    for idx in indices:
        info = info_list[idx]
        raw_index = raw_indices[idx]
        token = str(info.get('token', idx))
        out_file = osp.join(args.out_dir, f'{idx:06d}_{safe_token(token)}.png')
        if args.skip_existing and osp.exists(out_file):
            print(f'[SKIP] {out_file}')
            summary.append(dict(index=idx, token=token, out_file=out_file,
                                skipped=True))
            frame_files.append(out_file)
            continue

        points = load_points(cfg, dataset_cfg, info)
        gt_data = gt_arrays_from_info(info, dataset_cfg, class_names,
                                      label_mapping)
        if pkl_results is not None:
            if idx >= len(pkl_results):
                print(f'[WARN] missing pkl result for index {idx}, skip')
                continue
            pred_data = pred_arrays_from_pkl_result(
                pkl_results[idx], args.score_thr, args.topk)
        else:
            pred_data = pred_arrays_from_json(
                json_results.get(token, []), class_names,
                args.score_thr, args.topk)

        render_frame(
            points=points,
            gt_data=gt_data,
            pred_data=pred_data,
            class_names=class_names,
            save_path=out_file,
            title_id=f'idx={idx} raw_idx={raw_index} token={token}',
            pc_range=cfg.point_cloud_range,
            vel_scale=args.vel_scale,
            min_vel_draw=args.min_vel_draw,
            point_stride=args.point_stride,
            annotate=args.annotate)
        summary.append(dict(
            index=int(idx),
            raw_index=int(raw_index),
            token=token,
            out_file=out_file,
            num_gt=int(len(gt_data['boxes'])),
            num_pred=int(len(pred_data['boxes']))))
        frame_files.append(out_file)
        print(f'[OK] {out_file}')

    with open(osp.join(args.out_dir, 'summary.json'), 'w') as f:
        json.dump(summary, f, indent=2)
    write_html_player(args.out_dir, frame_files)
    write_webm_video(args.out_dir, fps=args.webm_fps, crf=args.webm_crf)


if __name__ == '__main__':
    main()
