#!/usr/bin/env python
"""Inspect KL occupancy GT generation used by the LiDAR OccHead config."""

import argparse
import copy
import json
import os
import os.path as osp
import sys
from collections import Counter, defaultdict

os.environ.setdefault('MPLCONFIGDIR', '/tmp/matplotlib-codex')
REPO_ROOT = osp.abspath(osp.join(osp.dirname(__file__), '..', '..'))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import mmcv
import numpy as np
import torch
from mmcv import Config
from mmcv.parallel import DataContainer as DC
from mmdet.datasets import build_dataset

import projects.mmdet3d_plugin  # noqa: F401
from projects.mmdet3d_plugin.datasets.pipelines.occflow_label import (
    GenerateOccFlowLabels,
)
from projects.mmdet3d_plugin.uniad.apis.test import _get_occ_eval_slices


def parse_args():
    parser = argparse.ArgumentParser(
        description='Audit KL occupancy GT labels generated by the config.')
    parser.add_argument(
        '--config',
        default='projects/configs/stage2_e2e_lidar/base_e2e_lidar_occ.py')
    parser.add_argument('--split', default='val', choices=['train', 'val', 'test'])
    parser.add_argument('--start-index', type=int, default=0)
    parser.add_argument('--max-samples', type=int, default=32)
    parser.add_argument('--stride', type=int, default=1)
    parser.add_argument(
        '--out-dir',
        default='projects/work_dirs/inspect_kl_occ_gt')
    parser.add_argument(
        '--num-visuals',
        type=int,
        default=4,
        help='number of inspected samples to render as BEV PNGs')
    parser.add_argument(
        '--ignore-index',
        type=int,
        default=255,
        help='ignore label used by GenerateOccFlowLabels')
    return parser.parse_args()


def unwrap(value):
    return value.data if isinstance(value, DC) else value


def to_numpy(value):
    value = unwrap(value)
    if torch.is_tensor(value):
        return value.detach().cpu().numpy()
    return np.asarray(value)


def find_pipeline_steps(pipeline, step_type):
    steps = []
    for step in pipeline:
        if isinstance(step, dict) and step.get('type') == step_type:
            steps.append(step)
        if isinstance(step, dict) and 'transforms' in step:
            steps.extend(find_pipeline_steps(step['transforms'], step_type))
    return steps


def get_split_cfg(cfg, split):
    data_cfg = copy.deepcopy(cfg.data[split])
    if split == 'train':
        # Make inspection deterministic. The train dataset normally retries
        # with random samples when an item is invalid.
        data_cfg.test_mode = True
    return data_cfg


def mapped_label(dataset, raw_label):
    if hasattr(dataset, '_map_label'):
        return int(dataset._map_label(raw_label))
    return int(raw_label)


def valid_instance(dataset, inst):
    if getattr(dataset, 'use_valid_flag', False):
        return bool(inst.get('bbox_3d_isvalid', True))
    return int(inst.get('num_lidar_pts', 1)) > 0


def collect_future_indices(dataset, raw_index):
    if hasattr(dataset, '_collect_occ_future_indices'):
        return dataset._collect_occ_future_indices(raw_index)
    n_future = int(getattr(dataset, 'occ_n_future', 4))
    scene_token = dataset.data_infos[raw_index].get('scene_token')
    out = []
    cursor = dataset.data_infos[raw_index]
    next_token = cursor.get('next', '')
    for _ in range(n_future):
        next_idx = dataset.token2index.get(next_token, -1) if next_token else -1
        if next_idx < 0 or dataset.data_infos[next_idx].get('scene_token') != scene_token:
            out.append(-1)
            next_token = ''
            continue
        out.append(next_idx)
        next_token = dataset.data_infos[next_idx].get('next', '')
    return out


def class_filter_stats(dataset, raw_index, filter_cls_ids):
    filter_cls_ids = set(int(v) for v in filter_cls_ids)
    future_frames = [raw_index] + collect_future_indices(dataset, raw_index)
    before = Counter()
    after = Counter()
    raw_track_ids = []
    kept_track_ids = []
    invalid_frames = 0

    for frame_idx in future_frames:
        if frame_idx < 0:
            invalid_frames += 1
            continue
        for inst in dataset.data_infos[frame_idx].get('instances', []):
            if not valid_instance(dataset, inst):
                continue
            label = mapped_label(
                dataset,
                inst.get('bbox_label_3d', inst.get('bbox_label', -1)))
            if label < 0:
                continue
            track_id = int(inst.get('track_id', -1))
            raw_track_ids.append(track_id)
            before[label] += 1
            if label in filter_cls_ids:
                kept_track_ids.append(track_id)
                after[label] += 1

    return dict(
        future_frames=[int(v) for v in future_frames],
        invalid_future_frames=invalid_frames,
        before=dict(before),
        after=dict(after),
        raw_track_id_min=min(raw_track_ids) if raw_track_ids else None,
        raw_track_id_max=max(raw_track_ids) if raw_track_ids else None,
        raw_track_id_zero_count=sum(1 for v in raw_track_ids if v == 0),
        kept_track_id_zero_count=sum(1 for v in kept_track_ids if v == 0),
        kept_box_count=sum(after.values()))


def occ_sample_stats(sample, ignore_index):
    seg = to_numpy(sample['gt_segmentation'])
    inst = to_numpy(sample['gt_instance'])
    img_valid = to_numpy(sample['gt_occ_img_is_valid']).astype(bool)
    has_invalid = bool(unwrap(sample['gt_occ_has_invalid_frame']))

    if seg.ndim != 3 or inst.ndim != 3:
        raise AssertionError(
            f'Expected gt_segmentation/gt_instance [T,H,W], got '
            f'{seg.shape} and {inst.shape}.')

    t, h, w = seg.shape
    unique_seg = sorted(int(v) for v in np.unique(seg))
    unique_inst = sorted(int(v) for v in np.unique(inst))
    fg_pixels = [int((seg[i] == 1).sum()) for i in range(t)]
    ignore_pixels = [int((seg[i] == ignore_index).sum()) for i in range(t)]
    instance_counts = []
    id_to_frames = defaultdict(list)
    for step in range(t):
        ids = np.unique(inst[step])
        ids = [int(v) for v in ids if v not in (0, ignore_index)]
        instance_counts.append(len(ids))
        for ins_id in ids:
            id_to_frames[ins_id].append(step)

    discontinuous_ids = []
    for ins_id, frames in id_to_frames.items():
        if frames != list(range(frames[0], frames[-1] + 1)):
            discontinuous_ids.append((ins_id, frames))

    expected_valid_len = t + 2
    future_valid = img_valid[-t:] if img_valid.size >= t else img_valid
    invalid_frame_checks = []
    for step, valid in enumerate(future_valid):
        if not valid:
            invalid_frame_checks.append(
                bool(np.all(seg[step] == ignore_index)
                     and np.all(inst[step] == ignore_index)))

    errors = []
    if seg.shape != inst.shape:
        errors.append('segmentation and instance shapes differ')
    if img_valid.size != expected_valid_len:
        errors.append(
            f'gt_occ_img_is_valid length {img_valid.size}, expected {expected_valid_len}')
    bad_seg_values = [v for v in unique_seg if v not in (0, 1, ignore_index)]
    if bad_seg_values:
        errors.append(f'unexpected segmentation labels: {bad_seg_values}')
    if any(not ok for ok in invalid_frame_checks):
        errors.append('invalid future frame is not filled by ignore_index')

    return dict(
        shape=[int(t), int(h), int(w)],
        gt_occ_img_is_valid=[bool(v) for v in img_valid.tolist()],
        gt_occ_has_invalid_frame=has_invalid,
        unique_seg=unique_seg,
        unique_instance_min=int(min(unique_inst)) if unique_inst else None,
        unique_instance_max=int(max(unique_inst)) if unique_inst else None,
        foreground_pixels=fg_pixels,
        ignore_pixels=ignore_pixels,
        instance_counts=instance_counts,
        discontinuous_instance_ids=discontinuous_ids[:20],
        errors=errors)


def eval_slice_report(grid_conf, shape):
    dummy = torch.zeros((1, 1, 1, shape[0], shape[1]))
    out = {}
    x_min, _, dx = [float(v) for v in grid_conf['xbound']]
    y_min, _, dy = [float(v) for v in grid_conf['ybound']]
    for key in ('30x30', '100x100'):
        y_slice, x_slice = _get_occ_eval_slices(key, dummy)
        x0 = x_min + x_slice.start * dx
        x1 = x_min + x_slice.stop * dx
        y0 = y_min + y_slice.start * dy
        y1 = y_min + y_slice.stop * dy
        out[key] = dict(
            y_slice=[int(y_slice.start), int(y_slice.stop)],
            x_slice=[int(x_slice.start), int(x_slice.stop)],
            meters=[round(x0, 3), round(x1, 3),
                    round(y0, 3), round(y1, 3)],
            size_m=[round(x1 - x0, 3), round(y1 - y0, 3)])
    return out


def build_occ_generator(pipeline_cfg):
    occ_steps = find_pipeline_steps(pipeline_cfg, 'GenerateOccFlowLabels')
    if not occ_steps:
        raise KeyError('GenerateOccFlowLabels not found in the configured pipeline.')
    occ_cfg = copy.deepcopy(occ_steps[0])
    occ_cfg.pop('type')
    return GenerateOccFlowLabels(**occ_cfg), occ_cfg


def build_ref_boxes(dataset, raw_index, occ_generator, filter_cls_ids):
    occ_inputs = dataset._build_occ_inputs(raw_index)
    ann_infos = occ_inputs['occ_future_ann_infos']
    l2e_r = occ_inputs['occ_l2e_r_mats']
    l2e_t = occ_inputs['occ_l2e_t_vecs']
    e2g_r = occ_inputs['occ_e2g_r_mats']
    e2g_t = occ_inputs['occ_e2g_t_vecs']
    t_ref = dict(l2e_r=l2e_r[0], l2e_t=l2e_t[0],
                 e2g_r=e2g_r[0], e2g_t=e2g_t[0])
    filter_cls_ids = set(int(v) for v in filter_cls_ids)

    boxes_per_step = []
    for step, ann in enumerate(ann_infos):
        if ann is None:
            boxes_per_step.append([])
            continue
        t_curr = dict(l2e_r=l2e_r[step], l2e_t=l2e_t[step],
                      e2g_r=e2g_r[step], e2g_t=e2g_t[step])
        boxes = occ_generator.reframe_boxes(
            copy.deepcopy(ann['gt_bboxes_3d']), t_ref, t_curr)
        labels = np.asarray(ann['gt_labels_3d'])
        inds = np.asarray(ann['gt_inds']) + 1
        keep = np.isin(labels, list(filter_cls_ids))
        boxes = boxes[keep]
        labels = labels[keep]
        inds = inds[keep]
        entries = []
        if len(boxes.tensor) > 0:
            corners = boxes.corners[:, [0, 3, 7, 4], :2].detach().cpu().numpy()
            centers = boxes.tensor[:, :2].detach().cpu().numpy()
            yaws = boxes.tensor[:, 6].detach().cpu().numpy()
            for i in range(len(corners)):
                entries.append(
                    dict(
                        corners=corners[i],
                        center=centers[i],
                        yaw=float(yaws[i]),
                        label=int(labels[i]),
                        instance_id=int(inds[i])))
        boxes_per_step.append(entries)
    return boxes_per_step


def world_to_grid_xy(points_xy, grid_conf):
    resolution = np.asarray([grid_conf['xbound'][2], grid_conf['ybound'][2]],
                            dtype=np.float32)
    start = np.asarray([
        grid_conf['xbound'][0] + grid_conf['xbound'][2] / 2.0,
        grid_conf['ybound'][0] + grid_conf['ybound'][2] / 2.0,
    ], dtype=np.float32)
    return np.round((points_xy - start + resolution / 2.0) /
                    resolution).astype(np.int32)


def render_sample(out_dir, dataset, raw_index, dataset_index, sample, grid_conf,
                  occ_generator, filter_cls_ids, ignore_index):
    seg = to_numpy(sample['gt_segmentation'])
    inst = to_numpy(sample['gt_instance'])
    boxes_per_step = build_ref_boxes(dataset, raw_index, occ_generator,
                                     filter_cls_ids)
    t, h, w = seg.shape
    fig, axes = plt.subplots(1, t, figsize=(4 * t, 4), squeeze=False)
    axes = axes[0]
    token = dataset.data_infos[raw_index].get('token', str(raw_index))

    for step, ax in enumerate(axes):
        rgb = np.ones((h, w, 3), dtype=np.float32)
        rgb[seg[step] == 1] = np.asarray([0.18, 0.45, 0.85])
        rgb[seg[step] == ignore_index] = np.asarray([0.82, 0.82, 0.82])
        ax.imshow(rgb, origin='lower')
        ids = np.unique(inst[step])
        ids = [int(v) for v in ids if v not in (0, ignore_index)]
        for entry in boxes_per_step[step]:
            poly = world_to_grid_xy(entry['corners'], grid_conf)
            center = world_to_grid_xy(entry['center'][None, :], grid_conf)[0]
            poly_closed = np.vstack([poly, poly[0]])
            ax.plot(poly_closed[:, 0], poly_closed[:, 1],
                    color='#f97316', linewidth=1.2)
            arrow_len = 6.0
            ax.arrow(center[0], center[1],
                     np.cos(entry['yaw']) * arrow_len,
                     np.sin(entry['yaw']) * arrow_len,
                     width=0.35, color='#111827', length_includes_head=True)
        ax.set_title(
            f't+{step}: fg={int((seg[step] == 1).sum())}, ids={len(ids)}',
            fontsize=10)
        ax.set_xlim(0, w - 1)
        ax.set_ylim(0, h - 1)
        ax.set_aspect('equal')
        ax.grid(color='white', linewidth=0.25, alpha=0.25)

    fig.suptitle(f'dataset_idx={dataset_index}, raw_idx={raw_index}, token={token}')
    fig.tight_layout()
    safe_token = str(token).replace('/', '_')[:64]
    out_path = osp.join(out_dir, f'occ_gt_{dataset_index:06d}_{safe_token}.png')
    fig.savefig(out_path, dpi=140)
    plt.close(fig)
    return out_path


def synthetic_grid_check(occ_generator, grid_conf, ignore_index):
    # A 4m x 2m box centered at ego origin should land near the grid center.
    from mmdet3d.core.bbox import LiDARInstance3DBoxes

    box = np.asarray([[0.0, 0.0, 0.0, 4.0, 2.0, 1.5, 0.0, 0.0, 0.0]],
                     dtype=np.float32)
    boxes = LiDARInstance3DBoxes(box, box_dim=9, origin=(0.5, 0.5, 0.5))
    identity = torch.eye(3, dtype=torch.float32)
    zero = torch.zeros(3, dtype=torch.float32)
    results = dict(
        future_gt_bboxes_3d=[boxes],
        future_gt_labels_3d=[np.asarray([1], dtype=np.int64)],
        future_gt_inds=[np.asarray([1], dtype=np.int64)],
        future_gt_vis_tokens=[None],
        occ_l2e_r_mats=[identity],
        occ_l2e_t_vecs=[zero],
        occ_e2g_r_mats=[identity],
        occ_e2g_t_vecs=[zero],
        occ_has_invalid_frame=False,
        occ_img_is_valid=np.asarray([True], dtype=np.bool_))
    out = occ_generator(copy.deepcopy(results))
    seg = out['gt_segmentation'].numpy()[0]
    ys, xs = np.nonzero(seg == 1)
    expected_center = world_to_grid_xy(np.asarray([[0.0, 0.0]],
                                                 dtype=np.float32), grid_conf)[0]
    ok = len(xs) > 0
    actual_center = [float(xs.mean()), float(ys.mean())] if ok else None
    return dict(
        ok=bool(ok),
        shape=[int(v) for v in seg.shape],
        expected_center_cell=[int(expected_center[0]), int(expected_center[1])],
        actual_center_cell=actual_center,
        foreground_pixels=int((seg == 1).sum()),
        ignore_index=int(ignore_index))


def main():
    args = parse_args()
    mmcv.mkdir_or_exist(args.out_dir)
    cfg = Config.fromfile(args.config)
    split_cfg = get_split_cfg(cfg, args.split)
    dataset = build_dataset(split_cfg)
    occ_generator, occ_cfg = build_occ_generator(split_cfg.pipeline)
    grid_conf = occ_cfg['grid_conf']
    filter_cls_ids = occ_cfg.get('filter_cls_ids', [])

    max_end = min(len(dataset), args.start_index + args.max_samples * args.stride)
    dataset_indices = list(range(args.start_index, max_end, args.stride))

    report = dict(
        config=args.config,
        split=args.split,
        dataset_type=type(dataset).__name__,
        dataset_len=len(dataset),
        grid_conf=grid_conf,
        filter_cls_ids=[int(v) for v in filter_cls_ids],
        occ_receptive_field=int(getattr(dataset, 'occ_receptive_field', 0)),
        occ_n_future=int(getattr(dataset, 'occ_n_future', 0)),
        expected_shape=[
            int(getattr(dataset, 'occ_n_future', 4)) + 1,
            int((grid_conf['ybound'][1] - grid_conf['ybound'][0]) /
                grid_conf['ybound'][2]),
            int((grid_conf['xbound'][1] - grid_conf['xbound'][0]) /
                grid_conf['xbound'][2]),
        ],
        eval_slices=eval_slice_report(
            grid_conf,
            shape=(
                int((grid_conf['ybound'][1] - grid_conf['ybound'][0]) /
                    grid_conf['ybound'][2]),
                int((grid_conf['xbound'][1] - grid_conf['xbound'][0]) /
                    grid_conf['xbound'][2]))),
        synthetic_grid_check=synthetic_grid_check(
            occ_generator, grid_conf, args.ignore_index),
        samples=[],
        totals=dict(
            errors=Counter(),
            class_before=Counter(),
            class_after=Counter(),
            invalid_samples=0,
            foreground_pixels=0,
            kept_boxes=0,
            raw_track_id_zero_count=0,
            kept_track_id_zero_count=0))

    visual_count = 0
    for dataset_index in dataset_indices:
        raw_index = (dataset._to_raw_index(dataset_index)
                     if hasattr(dataset, '_to_raw_index') else dataset_index)
        sample = dataset[dataset_index]
        if sample is None:
            item = dict(dataset_index=dataset_index,
                        raw_index=raw_index,
                        errors=['dataset returned None'])
            report['samples'].append(item)
            report['totals']['invalid_samples'] += 1
            report['totals']['errors']['dataset returned None'] += 1
            continue

        stats = occ_sample_stats(sample, args.ignore_index)
        class_stats = class_filter_stats(dataset, raw_index, filter_cls_ids)
        item = dict(
            dataset_index=int(dataset_index),
            raw_index=int(raw_index),
            token=dataset.data_infos[raw_index].get('token', ''),
            scene_token=dataset.data_infos[raw_index].get('scene_token', ''),
            occ=stats,
            class_filter=class_stats)

        for label, count in class_stats['before'].items():
            report['totals']['class_before'][int(label)] += int(count)
        for label, count in class_stats['after'].items():
            report['totals']['class_after'][int(label)] += int(count)
        report['totals']['foreground_pixels'] += sum(stats['foreground_pixels'])
        report['totals']['kept_boxes'] += int(class_stats['kept_box_count'])
        report['totals']['raw_track_id_zero_count'] += int(
            class_stats['raw_track_id_zero_count'])
        report['totals']['kept_track_id_zero_count'] += int(
            class_stats['kept_track_id_zero_count'])
        for error in stats['errors']:
            report['totals']['errors'][error] += 1

        if visual_count < args.num_visuals:
            item['visualization'] = render_sample(
                args.out_dir, dataset, raw_index, dataset_index, sample,
                grid_conf, occ_generator, filter_cls_ids, args.ignore_index)
            visual_count += 1

        report['samples'].append(item)

    report['totals']['errors'] = dict(report['totals']['errors'])
    report['totals']['class_before'] = dict(report['totals']['class_before'])
    report['totals']['class_after'] = dict(report['totals']['class_after'])
    report_path = osp.join(args.out_dir, 'inspect_kl_occ_gt_report.json')
    with open(report_path, 'w', encoding='utf-8') as f:
        json.dump(report, f, indent=2)

    print(f'wrote report: {report_path}')
    print('dataset:', report['dataset_type'], 'len=', report['dataset_len'])
    print('expected_shape:', report['expected_shape'])
    print('eval_slices:', report['eval_slices'])
    print('synthetic_grid_check:', report['synthetic_grid_check'])
    print('class_before:', report['totals']['class_before'])
    print('class_after:', report['totals']['class_after'])
    print('errors:', report['totals']['errors'])
    print('foreground_pixels:', report['totals']['foreground_pixels'])
    print('kept_boxes:', report['totals']['kept_boxes'])
    print('track_id_zero_counts:',
          report['totals']['raw_track_id_zero_count'],
          report['totals']['kept_track_id_zero_count'])


if __name__ == '__main__':
    main()
