#!/usr/bin/env python
"""Visualize KL drivable-space GT generated from the HD map.

This is a data-side smoke test before wiring a map segmentation head into the
LiDAR track config. It parses ``data/kl_8/map/base_map.txt``, builds a global
drivable geometry, projects it into each sample's ego frame, rasterizes it to
the LiDAR BEV canvas, and overlays the mask with points and GT boxes. The
optional LiDAR-ground augmentation is deliberately conservative and intended
for visual validation before it is used as training supervision.

Example:
    python tools/analysis_tools/visualize_kl_drivable_gt.py \
        --ann-file data/kl_8/kl_infos_val.pkl \
        --map-file data/kl_8/map/base_map.txt \
        --indices 0 100 500 1000 \
        --out-dir projects/work_dirs/debug_kl_drivable_gt
"""

from __future__ import annotations

import argparse
import json
import math
import os
import os.path as osp
import pickle
import re
import sys
from dataclasses import dataclass, field
from typing import Iterable, List, Optional, Sequence, Tuple

os.environ.setdefault('MPLCONFIGDIR', '/tmp/matplotlib')
REPO_ROOT = osp.abspath(osp.join(osp.dirname(__file__), '..', '..'))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

import cv2
import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from shapely import affinity, ops
from shapely.geometry import GeometryCollection, MultiPolygon, Polygon, box

from projects.mmdet3d_plugin.datasets.pipelines.kl_drivable_label import (
    build_map_mask as pipeline_build_map_mask,
    load_clean_drivable_geometry,
)


DEFAULT_PC_RANGE = (-64.0, -48.0, -2.0, 64.0, 48.0, 6.0)
DEFAULT_BEV_SIZE = (120, 160)
DEFAULT_CLASS_NAMES = (
    'Pedestrian', 'Car', 'IGV-Full', 'Truck', 'Trailer-Empty',
    'Trailer-Full', 'IGV-Empty', 'Crane', 'OtherVehicle', 'Cone',
    'ContainerForklift', 'Forklift', 'WheelCrane',
)
DEFAULT_LABEL_MAPPING = (
    0, 1, 2, 3, 4,
    5, 6, 7, 8, 9,
    10, 11, 8, 8, 12,
)
DRIVABLE_LABEL = 3


@dataclass
class MapStats:
    lanes: int = 0
    lane_polygons: int = 0
    roads: int = 0
    road_polygons: int = 0
    junctions: int = 0
    drivable_junctions: int = 0
    blocking_junctions: int = 0
    electric_fences: int = 0
    not_drivable_fences: int = 0
    parking_lots: int = 0
    parking_lot_polygons: int = 0
    positive_area: float = 0.0
    negative_area: float = 0.0
    drivable_area: float = 0.0
    warnings: List[str] = field(default_factory=list)


@dataclass
class DrivableTarget:
    mask: np.ndarray
    gt_lane_labels: np.ndarray
    gt_lane_bboxes: np.ndarray
    gt_lane_masks: np.ndarray
    map_mask: Optional[np.ndarray] = None
    lidar_ground_mask: Optional[np.ndarray] = None
    lidar_obstacle_mask: Optional[np.ndarray] = None
    raycast_free_mask: Optional[np.ndarray] = None
    augmentation: str = 'map'


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Visualize KL drivable GT from base_map.txt.')
    parser.add_argument(
        '--ann-file',
        default='data/kl_8/kl_infos_val.pkl',
        help='KL info pickle, e.g. data/kl_8/kl_infos_val.pkl')
    parser.add_argument(
        '--map-file',
        default='data/kl_8/map/base_map.txt',
        help='Apollo text HD map file.')
    parser.add_argument(
        '--clean-map-file',
        default=None,
        help='clean drivable map pkl generated by prepare_kl_drivable_map.py.')
    parser.add_argument(
        '--data-root',
        default='data/kl_8',
        help='dataset root used to resolve relative LiDAR paths.')
    parser.add_argument(
        '--pts-prefix',
        default='v1.0-trainval/samples',
        help='relative point cloud prefix inside --data-root.')
    parser.add_argument(
        '--out-dir',
        default='projects/work_dirs/debug_kl_drivable_gt',
        help='directory for PNG/NPZ/HTML outputs.')
    parser.add_argument('--start-index', type=int, default=0)
    parser.add_argument('--max-samples', type=int, default=4)
    parser.add_argument('--indices', type=int, nargs='*', default=None)
    parser.add_argument('--token', default=None)
    parser.add_argument('--scene-token', default=None)
    parser.add_argument(
        '--pc-range',
        type=float,
        nargs=6,
        default=list(DEFAULT_PC_RANGE),
        help='x_min y_min z_min x_max y_max z_max in ego/LiDAR frame.')
    parser.add_argument(
        '--bev-size',
        type=int,
        nargs=2,
        default=list(DEFAULT_BEV_SIZE),
        metavar=('H', 'W'))
    parser.add_argument('--point-stride', type=int, default=4)
    parser.add_argument('--mask-alpha', type=float, default=0.38)
    parser.add_argument(
        '--include-parking-lot',
        action='store_true',
        help='include parking_lot polygons as drivable.')
    parser.add_argument(
        '--no-lanes',
        action='store_true',
        help='do not include lane boundary ribbons as positive geometry.')
    parser.add_argument(
        '--no-roads',
        action='store_true',
        help='do not include road outer polygons as positive geometry.')
    parser.add_argument(
        '--no-junctions',
        action='store_true',
        help='do not include non-blocking junction polygons as positive geometry.')
    parser.add_argument(
        '--no-negative',
        action='store_true',
        help='do not subtract electric_fence/BLOCKING_AREA polygons.')
    parser.add_argument(
        '--save-npz',
        action='store_true',
        help='save generated Pansegformer-style targets per frame.')
    parser.add_argument(
        '--augment-lidar-ground',
        action='store_true',
        help='union HD-map drivable mask with a LiDAR ground-support mask.')
    parser.add_argument(
        '--augment-raycast-ground',
        action='store_true',
        help='union HD-map drivable mask with raycast OCC-derived ground.')
    parser.add_argument(
        '--keep-raycast-obstacles',
        action='store_true',
        help='keep HD-map/raycast drivable cells even when raycast sees obstacles.')
    parser.add_argument(
        '--raycast-occ-size',
        type=int,
        nargs=3,
        default=[200, 120, 10],
        metavar=('X', 'Y', 'Z'),
        help='raycast OCC voxel grid size. X/Y should match BEV W/H.')
    parser.add_argument(
        '--raycast-ground-height-threshold',
        type=float,
        default=0.55)
    parser.add_argument(
        '--raycast-ground-smooth-radius',
        type=int,
        default=3)
    parser.add_argument(
        '--no-raycast-fill-ground',
        action='store_true')
    parser.add_argument(
        '--raycast-ground-fill-radius',
        type=int,
        default=2)
    parser.add_argument(
        '--raycast-ground-fill-min-neighbors',
        type=int,
        default=5)
    parser.add_argument(
        '--no-raycast-remove-ground-under-obstacle',
        action='store_true')
    parser.add_argument(
        '--raycast-obstacle-min-points-per-voxel',
        type=int,
        default=2)
    parser.add_argument(
        '--raycast-obstacle-min-component-voxels',
        type=int,
        default=8)
    parser.add_argument(
        '--raycast-obstacle-small-component-keep-min-points',
        type=int,
        default=300)
    parser.add_argument(
        '--raycast-obstacle-thin-component-min-major-span',
        type=float,
        default=4.0)
    parser.add_argument(
        '--raycast-obstacle-thin-component-max-minor-span',
        type=float,
        default=2.4)
    parser.add_argument(
        '--raycast-obstacle-thin-component-max-z-span',
        type=float,
        default=1.6)
    parser.add_argument(
        '--raycast-obstacle-thin-component-keep-min-points',
        type=int,
        default=300)
    parser.add_argument(
        '--raycast-obstacle-box-ignore-margin',
        type=float,
        default=0.8)
    parser.add_argument(
        '--raycast-ego-ignore-range',
        type=float,
        nargs=6,
        default=[-8.0, -2.0, -2.0, 8.0, 2.0, 6.0],
        help='cells in this ego box are ignored/removed from raycast masks.')
    parser.add_argument(
        '--ground-z-min',
        type=float,
        default=-1.2,
        help='minimum point z for LiDAR ground support.')
    parser.add_argument(
        '--ground-z-max',
        type=float,
        default=0.35,
        help='maximum point z for LiDAR ground support.')
    parser.add_argument(
        '--ground-min-points',
        type=int,
        default=3,
        help='minimum low-z LiDAR points for a BEV cell to become ground.')
    parser.add_argument(
        '--ground-close-kernel',
        type=int,
        default=3,
        help='odd morphology close kernel for LiDAR ground mask; <=1 disables.')
    parser.add_argument(
        '--ground-close-iters',
        type=int,
        default=1)
    parser.add_argument(
        '--ground-dilate-kernel',
        type=int,
        default=3,
        help='odd morphology dilation kernel for LiDAR ground mask; <=1 disables.')
    parser.add_argument(
        '--ground-dilate-iters',
        type=int,
        default=1)
    parser.add_argument(
        '--ground-min-component-area',
        type=int,
        default=18,
        help='remove connected LiDAR-ground islands smaller than this many cells.')
    parser.add_argument(
        '--no-reject-lidar-obstacles',
        action='store_true',
        help='do not remove cells with vertical/high LiDAR obstacle evidence.')
    parser.add_argument(
        '--obstacle-z-min',
        type=float,
        default=0.70,
        help='points above this z are evidence for non-drivable obstacles.')
    parser.add_argument(
        '--obstacle-min-points',
        type=int,
        default=2,
        help='minimum high-z points for a BEV cell to become obstacle evidence.')
    parser.add_argument(
        '--obstacle-min-height-range',
        type=float,
        default=0.75,
        help='cell z range above this value is obstacle evidence.')
    parser.add_argument(
        '--obstacle-dilate-kernel',
        type=int,
        default=5,
        help='odd dilation kernel for obstacle rejection; <=1 disables.')
    parser.add_argument(
        '--obstacle-dilate-iters',
        type=int,
        default=1)
    parser.add_argument(
        '--no-remove-box-points',
        action='store_true',
        help='keep points inside GT boxes when estimating LiDAR ground/obstacles.')
    parser.add_argument(
        '--html-name',
        default='index.html',
        help='simple HTML viewer filename inside --out-dir.')
    args = parser.parse_args()
    if args.max_samples <= 0:
        raise ValueError('--max-samples must be positive.')
    if args.point_stride <= 0:
        raise ValueError('--point-stride must be positive.')
    if not 0.0 <= args.mask_alpha <= 1.0:
        raise ValueError('--mask-alpha must be in [0, 1].')
    if args.augment_lidar_ground and args.augment_raycast_ground:
        raise ValueError(
            'Choose only one of --augment-lidar-ground and '
            '--augment-raycast-ground.')
    return args


def load_infos(ann_file: str) -> List[dict]:
    with open(ann_file, 'rb') as f:
        data = pickle.load(f)
    if isinstance(data, dict) and 'data_list' in data:
        return data['data_list']
    if isinstance(data, dict) and 'infos' in data:
        return data['infos']
    if isinstance(data, list):
        return data
    raise TypeError(f'Unsupported info format: {type(data)}')


def find_block_end(text: str, open_brace_idx: int) -> int:
    depth = 0
    for idx in range(open_brace_idx, len(text)):
        ch = text[idx]
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                return idx
    raise ValueError('unbalanced braces while parsing map file')


def extract_blocks(text: str, name: str, anchored: bool = False) -> List[str]:
    prefix = r'^' if anchored else r''
    pattern = re.compile(prefix + re.escape(name) + r'\s*\{', re.MULTILINE)
    blocks = []
    for match in pattern.finditer(text):
        open_idx = text.find('{', match.start(), match.end())
        close_idx = find_block_end(text, open_idx)
        blocks.append(text[open_idx + 1:close_idx])
    return blocks


def extract_points(block: str) -> np.ndarray:
    pts = []
    for match in re.finditer(
            r'point\s*\{\s*x:\s*([-\d.eE+]+)\s*y:\s*([-\d.eE+]+)',
            block):
        pts.append((float(match.group(1)), float(match.group(2))))
    return np.asarray(pts, dtype=np.float64)


def extract_id(block: str) -> str:
    match = re.search(r'id:\s*"([^"]+)"', block)
    return match.group(1) if match else ''


def extract_type(block: str) -> str:
    match = re.search(r'(?m)^\s*type:\s*([A-Za-z0-9_]+)', block)
    return match.group(1) if match else ''


def keep_polygonal(geom):
    if geom is None or geom.is_empty:
        return None
    if isinstance(geom, (Polygon, MultiPolygon)):
        return geom
    if isinstance(geom, GeometryCollection):
        polys = [g for g in geom.geoms if isinstance(g, (Polygon, MultiPolygon))
                 and not g.is_empty]
        if not polys:
            return None
        return ops.unary_union(polys)
    return None


def polygon_from_points(points: np.ndarray, min_area: float = 0.5):
    if len(points) < 3:
        return None
    if np.linalg.norm(points[0] - points[-1]) > 1e-6:
        points = np.concatenate([points, points[:1]], axis=0)
    poly = Polygon(points)
    if not poly.is_valid:
        poly = poly.buffer(0)
    poly = keep_polygonal(poly)
    if poly is None or poly.is_empty or poly.area < min_area:
        return None
    return poly


def lane_polygon_from_block(block: str):
    left_blocks = extract_blocks(block, 'left_boundary')
    right_blocks = extract_blocks(block, 'right_boundary')
    if not left_blocks or not right_blocks:
        return None
    left = extract_points(left_blocks[0])
    right = extract_points(right_blocks[0])
    if len(left) < 2 or len(right) < 2:
        return None
    points = np.concatenate([left, right[::-1]], axis=0)
    return polygon_from_points(points, min_area=1.0)


def union_or_empty(geoms: Sequence):
    geoms = [geom for geom in geoms if geom is not None and not geom.is_empty]
    if not geoms:
        return GeometryCollection()
    return ops.unary_union(geoms)


def build_drivable_geometry(args: argparse.Namespace):
    with open(args.map_file, 'r') as f:
        text = f.read()

    stats = MapStats()
    positives = []
    negatives = []

    lane_blocks = extract_blocks(text, 'lane', anchored=True)
    stats.lanes = len(lane_blocks)
    if not args.no_lanes:
        for block in lane_blocks:
            geom = lane_polygon_from_block(block)
            if geom is not None:
                positives.append(geom)
                stats.lane_polygons += 1

    road_blocks = extract_blocks(text, 'road', anchored=True)
    stats.roads = len(road_blocks)
    if not args.no_roads:
        for block in road_blocks:
            for outer in extract_blocks(block, 'outer_polygon'):
                geom = polygon_from_points(extract_points(outer), min_area=1.0)
                if geom is not None:
                    positives.append(geom)
                    stats.road_polygons += 1

    junction_blocks = extract_blocks(text, 'junction', anchored=True)
    stats.junctions = len(junction_blocks)
    for block in junction_blocks:
        jtype = extract_type(block)
        geom = polygon_from_points(extract_points(block), min_area=1.0)
        if geom is None:
            continue
        if 'BLOCKING' in jtype or 'NOT_DRIVABLE' in jtype:
            negatives.append(geom)
            stats.blocking_junctions += 1
        elif not args.no_junctions:
            positives.append(geom)
            stats.drivable_junctions += 1

    fence_blocks = extract_blocks(text, 'electric_fence', anchored=True)
    stats.electric_fences = len(fence_blocks)
    for block in fence_blocks:
        geom = polygon_from_points(extract_points(block), min_area=1.0)
        if geom is None:
            continue
        if extract_type(block) == 'NOT_DRIVABLE':
            negatives.append(geom)
            stats.not_drivable_fences += 1

    parking_lot_blocks = extract_blocks(text, 'parking_lot', anchored=True)
    stats.parking_lots = len(parking_lot_blocks)
    if args.include_parking_lot:
        for block in parking_lot_blocks:
            geom = polygon_from_points(extract_points(block), min_area=1.0)
            if geom is not None:
                positives.append(geom)
                stats.parking_lot_polygons += 1

    positive = keep_polygonal(union_or_empty(positives))
    negative = keep_polygonal(union_or_empty(negatives))
    if positive is None:
        positive = GeometryCollection()
    if negative is None:
        negative = GeometryCollection()

    stats.positive_area = float(positive.area)
    stats.negative_area = float(negative.area)
    if args.no_negative or negative.is_empty:
        drivable = positive
    else:
        drivable = keep_polygonal(positive.difference(negative))
        if drivable is None:
            drivable = GeometryCollection()
    if not drivable.is_valid:
        drivable = drivable.buffer(0)
    drivable = keep_polygonal(drivable)
    if drivable is None:
        drivable = GeometryCollection()
    stats.drivable_area = float(drivable.area)

    if stats.road_polygons == 0 and not args.no_roads:
        stats.warnings.append('No valid road polygons were parsed.')
    if stats.drivable_area <= 0:
        stats.warnings.append('Final drivable geometry is empty.')
    return drivable, stats


def transform_global_geom_to_ego(geom, ego2global: np.ndarray):
    g2e = np.linalg.inv(np.asarray(ego2global, dtype=np.float64))

    def fn(x, y, z=None):
        x_arr = np.asarray(x)
        y_arr = np.asarray(y)
        xe = g2e[0, 0] * x_arr + g2e[0, 1] * y_arr + g2e[0, 3]
        ye = g2e[1, 0] * x_arr + g2e[1, 1] * y_arr + g2e[1, 3]
        return xe, ye

    return ops.transform(fn, geom)


def iter_polygons(geom) -> Iterable[Polygon]:
    if geom is None or geom.is_empty:
        return
    if isinstance(geom, Polygon):
        yield geom
    elif isinstance(geom, MultiPolygon):
        for poly in geom.geoms:
            if not poly.is_empty:
                yield poly
    elif isinstance(geom, GeometryCollection):
        for part in geom.geoms:
            yield from iter_polygons(part)


def coords_to_mask_pixels(coords: np.ndarray, pc_range: Sequence[float],
                          bev_size: Sequence[int]) -> np.ndarray:
    x_min, y_min, _, x_max, y_max, _ = [float(v) for v in pc_range]
    bev_h, bev_w = int(bev_size[0]), int(bev_size[1])
    xs = coords[:, 0]
    ys = coords[:, 1]
    cols = (xs - x_min) / (x_max - x_min) * bev_w
    rows = (y_max - ys) / (y_max - y_min) * bev_h
    pix = np.stack([cols, rows], axis=1)
    pix = np.round(pix).astype(np.int32)
    pix[:, 0] = np.clip(pix[:, 0], 0, bev_w - 1)
    pix[:, 1] = np.clip(pix[:, 1], 0, bev_h - 1)
    return pix


def rasterize_ego_geometry(geom, pc_range: Sequence[float],
                           bev_size: Sequence[int]) -> np.ndarray:
    x_min, y_min, _, x_max, y_max, _ = [float(v) for v in pc_range]
    bev_h, bev_w = int(bev_size[0]), int(bev_size[1])
    crop = box(x_min, y_min, x_max, y_max)
    clipped = keep_polygonal(geom.intersection(crop))
    mask = np.zeros((bev_h, bev_w), dtype=np.uint8)
    if clipped is None or clipped.is_empty:
        return mask

    for poly in iter_polygons(clipped):
        exterior = np.asarray(poly.exterior.coords, dtype=np.float64)
        if len(exterior) >= 3:
            cv2.fillPoly(
                mask,
                [coords_to_mask_pixels(exterior, pc_range, bev_size)],
                color=1)
        for interior in poly.interiors:
            hole = np.asarray(interior.coords, dtype=np.float64)
            if len(hole) >= 3:
                cv2.fillPoly(
                    mask,
                    [coords_to_mask_pixels(hole, pc_range, bev_size)],
                    color=0)
    return mask


def target_from_mask(mask: np.ndarray) -> DrivableTarget:
    ys, xs = np.where(mask > 0)
    if len(xs) == 0:
        bboxes = np.zeros((0, 4), dtype=np.float32)
        labels = np.zeros((0,), dtype=np.int64)
        masks = np.zeros((0,) + mask.shape, dtype=np.uint8)
    else:
        bboxes = np.asarray(
            [[xs.min(), ys.min(), xs.max(), ys.max()]], dtype=np.float32)
        labels = np.asarray([DRIVABLE_LABEL], dtype=np.int64)
        masks = mask[None].astype(np.uint8)
    return DrivableTarget(
        mask=mask,
        gt_lane_labels=labels,
        gt_lane_bboxes=bboxes,
        gt_lane_masks=masks)


def build_map_mask(drivable_global, info: dict, pc_range: Sequence[float],
                   bev_size: Sequence[int]) -> np.ndarray:
    return pipeline_build_map_mask(
        drivable_global,
        np.asarray(info.get('ego2global', np.eye(4))),
        pc_range,
        bev_size)


def points_in_boxes_mask(points: np.ndarray,
                         boxes: np.ndarray,
                         xy_margin: float = 0.15,
                         z_margin: float = 0.2) -> np.ndarray:
    mask = np.zeros((len(points),), dtype=bool)
    if len(points) == 0 or len(boxes) == 0:
        return mask
    xy = points[:, :2].astype(np.float32)
    z = points[:, 2].astype(np.float32)
    for box_arr in boxes:
        x, y, zc, length, width, height, yaw = box_arr[:7]
        c = math.cos(float(yaw))
        s = math.sin(float(yaw))
        dx = xy[:, 0] - float(x)
        dy = xy[:, 1] - float(y)
        local_x = dx * c + dy * s
        local_y = -dx * s + dy * c
        inside_xy = (
            (np.abs(local_x) <= float(length) / 2.0 + xy_margin) &
            (np.abs(local_y) <= float(width) / 2.0 + xy_margin))
        inside_z = (
            (z >= float(zc) - float(height) / 2.0 - z_margin) &
            (z <= float(zc) + float(height) / 2.0 + z_margin))
        mask |= inside_xy & inside_z
    return mask


def cell_indices_from_points(points: np.ndarray, pc_range: Sequence[float],
                             bev_size: Sequence[int]):
    x_min, y_min, _, x_max, y_max, _ = [float(v) for v in pc_range]
    bev_h, bev_w = int(bev_size[0]), int(bev_size[1])
    x = points[:, 0]
    y = points[:, 1]
    valid = (
        (x >= x_min) & (x < x_max) & (y >= y_min) & (y < y_max))
    cols = ((x[valid] - x_min) / (x_max - x_min) * bev_w).astype(np.int32)
    rows = ((y_max - y[valid]) / (y_max - y_min) * bev_h).astype(np.int32)
    cols = np.clip(cols, 0, bev_w - 1)
    rows = np.clip(rows, 0, bev_h - 1)
    return rows, cols, valid


def remove_small_components(mask: np.ndarray, min_area: int) -> np.ndarray:
    if min_area <= 1 or mask.sum() == 0:
        return mask
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(
        mask.astype(np.uint8), connectivity=8)
    out = np.zeros_like(mask, dtype=np.uint8)
    for label in range(1, num_labels):
        if stats[label, cv2.CC_STAT_AREA] >= min_area:
            out[labels == label] = 1
    return out


def odd_kernel_size(value: int) -> int:
    value = int(value)
    if value <= 1:
        return value
    return value if value % 2 == 1 else value + 1


def point_count_mask(points: np.ndarray, pc_range: Sequence[float],
                     bev_size: Sequence[int], min_points: int) -> np.ndarray:
    bev_h, bev_w = int(bev_size[0]), int(bev_size[1])
    counts = np.zeros((bev_h, bev_w), dtype=np.uint16)
    if len(points) > 0:
        rows, cols, _ = cell_indices_from_points(points, pc_range, bev_size)
        np.add.at(counts, (rows, cols), 1)
    return (counts >= int(min_points)).astype(np.uint8)


def cell_height_range_mask(points: np.ndarray, pc_range: Sequence[float],
                           bev_size: Sequence[int],
                           min_height_range: float) -> np.ndarray:
    bev_h, bev_w = int(bev_size[0]), int(bev_size[1])
    if len(points) == 0 or min_height_range <= 0:
        return np.zeros((bev_h, bev_w), dtype=np.uint8)
    rows, cols, valid = cell_indices_from_points(points, pc_range, bev_size)
    z = points[valid, 2].astype(np.float32)
    if len(z) == 0:
        return np.zeros((bev_h, bev_w), dtype=np.uint8)

    z_min = np.full((bev_h, bev_w), np.inf, dtype=np.float32)
    z_max = np.full((bev_h, bev_w), -np.inf, dtype=np.float32)
    np.minimum.at(z_min, (rows, cols), z)
    np.maximum.at(z_max, (rows, cols), z)
    has_points = np.isfinite(z_min) & np.isfinite(z_max)
    height_range = np.zeros((bev_h, bev_w), dtype=np.float32)
    height_range[has_points] = z_max[has_points] - z_min[has_points]
    return (height_range >= float(min_height_range)).astype(np.uint8)


def dilate_mask(mask: np.ndarray, kernel_size: int, iters: int) -> np.ndarray:
    kernel_size = odd_kernel_size(kernel_size)
    if kernel_size <= 1 or iters <= 0 or mask.sum() == 0:
        return mask.astype(np.uint8)
    kernel = np.ones((kernel_size, kernel_size), dtype=np.uint8)
    return cv2.dilate(mask.astype(np.uint8), kernel, iterations=int(iters))


def lidar_ground_masks(points: np.ndarray, boxes: np.ndarray,
                       pc_range: Sequence[float], bev_size: Sequence[int],
                       args: argparse.Namespace) -> Tuple[np.ndarray, np.ndarray]:
    if len(points) == 0:
        empty = np.zeros(tuple(bev_size), dtype=np.uint8)
        return empty, empty

    pts = points[:, :3]
    x_min, y_min, z_min, x_max, y_max, z_max = [float(v) for v in pc_range]
    in_range = (
        (pts[:, 0] >= x_min) & (pts[:, 0] <= x_max) &
        (pts[:, 1] >= y_min) & (pts[:, 1] <= y_max) &
        (pts[:, 2] >= z_min) & (pts[:, 2] <= z_max))
    pts = pts[in_range]
    if not args.no_remove_box_points and len(boxes) > 0 and len(pts) > 0:
        pts = pts[~points_in_boxes_mask(pts, boxes)]

    bev_h, bev_w = int(bev_size[0]), int(bev_size[1])
    obstacle = np.zeros((bev_h, bev_w), dtype=np.uint8)
    if not args.no_reject_lidar_obstacles:
        high_pts = pts[pts[:, 2] >= float(args.obstacle_z_min)]
        high_mask = point_count_mask(
            high_pts, pc_range, bev_size, int(args.obstacle_min_points))
        height_mask = cell_height_range_mask(
            pts, pc_range, bev_size, float(args.obstacle_min_height_range))
        obstacle = np.maximum(high_mask, height_mask).astype(np.uint8)
        obstacle = dilate_mask(
            obstacle,
            int(args.obstacle_dilate_kernel),
            int(args.obstacle_dilate_iters))

    low = (
        (pts[:, 2] >= float(args.ground_z_min)) &
        (pts[:, 2] <= float(args.ground_z_max)))
    mask = point_count_mask(
        pts[low], pc_range, bev_size, int(args.ground_min_points))
    mask = np.logical_and(mask > 0, obstacle == 0).astype(np.uint8)

    close_k = odd_kernel_size(args.ground_close_kernel)
    if close_k > 1 and args.ground_close_iters > 0:
        kernel = np.ones((close_k, close_k), dtype=np.uint8)
        mask = cv2.morphologyEx(
            mask, cv2.MORPH_CLOSE, kernel,
            iterations=int(args.ground_close_iters))
        mask = np.logical_and(mask > 0, obstacle == 0).astype(np.uint8)

    dilate_k = odd_kernel_size(args.ground_dilate_kernel)
    if dilate_k > 1 and args.ground_dilate_iters > 0:
        kernel = np.ones((dilate_k, dilate_k), dtype=np.uint8)
        mask = cv2.dilate(mask, kernel, iterations=int(args.ground_dilate_iters))
        mask = np.logical_and(mask > 0, obstacle == 0).astype(np.uint8)

    mask = remove_small_components(mask, int(args.ground_min_component_area))
    return mask.astype(np.uint8), obstacle.astype(np.uint8)


class RaycastDrivableBuilder:
    """Small numpy port of KL raycast OCC ground/obstacle target generation."""

    def __init__(self, pc_range: Sequence[float], bev_size: Sequence[int],
                 args: argparse.Namespace) -> None:
        self.pc_range = np.asarray(pc_range, dtype=np.float32)
        self.occ_size = np.asarray(args.raycast_occ_size, dtype=np.int64)
        self.bev_h = int(bev_size[0])
        self.bev_w = int(bev_size[1])
        if self.occ_size.shape[0] != 3 or np.any(self.occ_size <= 0):
            raise ValueError(f'Invalid --raycast-occ-size: {self.occ_size}')
        if self.occ_size[0] != self.bev_w or self.occ_size[1] != self.bev_h:
            raise ValueError(
                '--raycast-occ-size X/Y must match --bev-size W/H, got '
                f'occ={self.occ_size.tolist()} bev={[self.bev_h, self.bev_w]}')

        self.voxel_size = (
            (self.pc_range[3:] - self.pc_range[:3]) /
            self.occ_size.astype(np.float32))
        self.ray_origin = np.zeros(3, dtype=np.float32)
        self.ground_height_threshold = float(
            args.raycast_ground_height_threshold)
        self.ground_smooth_radius = int(args.raycast_ground_smooth_radius)
        self.fill_ground = not bool(args.no_raycast_fill_ground)
        self.ground_fill_radius = int(args.raycast_ground_fill_radius)
        self.ground_fill_min_neighbors = int(
            args.raycast_ground_fill_min_neighbors)
        self.remove_ground_under_obstacle = not bool(
            args.no_raycast_remove_ground_under_obstacle)
        self.obstacle_min_points_per_voxel = int(
            args.raycast_obstacle_min_points_per_voxel)
        self.obstacle_min_component_voxels = int(
            args.raycast_obstacle_min_component_voxels)
        self.obstacle_small_component_keep_min_points = int(
            args.raycast_obstacle_small_component_keep_min_points)
        self.obstacle_thin_component_min_major_span = float(
            args.raycast_obstacle_thin_component_min_major_span)
        self.obstacle_thin_component_max_minor_span = float(
            args.raycast_obstacle_thin_component_max_minor_span)
        self.obstacle_thin_component_max_z_span = float(
            args.raycast_obstacle_thin_component_max_z_span)
        self.obstacle_thin_component_keep_min_points = int(
            args.raycast_obstacle_thin_component_keep_min_points)
        self.filter_thin_obstacle_components = (
            self.obstacle_thin_component_min_major_span > 0 and
            self.obstacle_thin_component_max_minor_span > 0 and
            self.obstacle_thin_component_max_z_span > 0)
        self.obstacle_box_ignore_margin = float(
            args.raycast_obstacle_box_ignore_margin)
        self.ego_ignore_range = (
            None if args.raycast_ego_ignore_range is None else
            np.asarray(args.raycast_ego_ignore_range, dtype=np.float32))

    def coord_to_index_floor(self, xyz: np.ndarray) -> np.ndarray:
        return np.floor((xyz - self.pc_range[:3]) / self.voxel_size).astype(
            np.int64)

    def coord_to_index_ceil(self, xyz: np.ndarray) -> np.ndarray:
        return np.ceil((xyz - self.pc_range[:3]) / self.voxel_size).astype(
            np.int64)

    def voxel_centers(self, axis: int, indices: np.ndarray) -> np.ndarray:
        return (self.pc_range[axis] +
                (indices.astype(np.float32) + 0.5) * self.voxel_size[axis])

    def box_voxel_indices(self, box_arr: np.ndarray):
        length, width, height = box_arr[3:6]
        if length <= 0 or width <= 0 or height <= 0:
            return None

        yaw = box_arr[6]
        cos_yaw = np.cos(yaw)
        sin_yaw = np.sin(yaw)
        dx = np.asarray([-0.5, -0.5, 0.5, 0.5], dtype=np.float32) * length
        dy = np.asarray([-0.5, 0.5, -0.5, 0.5], dtype=np.float32) * width
        x_corners = box_arr[0] + dx * cos_yaw - dy * sin_yaw
        y_corners = box_arr[1] + dx * sin_yaw + dy * cos_yaw

        corners_min = np.asarray(
            [x_corners.min(), y_corners.min(), box_arr[2]], dtype=np.float32)
        corners_max = np.asarray(
            [x_corners.max(), y_corners.max(), box_arr[2] + height],
            dtype=np.float32)
        lo = np.maximum(self.coord_to_index_floor(corners_min), 0)
        hi = np.minimum(self.coord_to_index_ceil(corners_max), self.occ_size)
        if np.any(hi <= lo):
            return None

        x_idx = np.arange(lo[0], hi[0], dtype=np.int64)
        y_idx = np.arange(lo[1], hi[1], dtype=np.int64)
        z_idx = np.arange(lo[2], hi[2], dtype=np.int64)
        if x_idx.size == 0 or y_idx.size == 0 or z_idx.size == 0:
            return None

        xs = self.voxel_centers(0, x_idx)
        ys = self.voxel_centers(1, y_idx)
        xx, yy = np.meshgrid(xs, ys, indexing='ij')
        rel_x = xx - box_arr[0]
        rel_y = yy - box_arr[1]
        local_x = rel_x * cos_yaw + rel_y * sin_yaw
        local_y = -rel_x * sin_yaw + rel_y * cos_yaw
        inside_xy = (
            (np.abs(local_x) <= length * 0.5) &
            (np.abs(local_y) <= width * 0.5))
        if not np.any(inside_xy):
            return None

        grid_x, grid_y = np.meshgrid(x_idx, y_idx, indexing='ij')
        return grid_x[inside_xy], grid_y[inside_xy], z_idx

    def box_interior_mask(self, boxes: np.ndarray) -> np.ndarray:
        mask = np.zeros(tuple(self.occ_size.tolist()), dtype=bool)
        for box_arr in boxes:
            indices = self.box_voxel_indices(box_arr)
            if indices is None:
                continue
            fill_x, fill_y, z_idx = indices
            mask[fill_x[:, None], fill_y[:, None], z_idx[None, :]] = True
        return mask

    def raycast_free_voxels(self, hit_voxels: np.ndarray) -> np.ndarray:
        if hit_voxels.shape[0] == 0:
            return np.empty((0, 3), dtype=np.int64)

        free_chunks = []
        origin = self.ray_origin
        for hit in hit_voxels:
            hit_center = (
                self.pc_range[:3] +
                (hit.astype(np.float32) + 0.5) * self.voxel_size)
            delta = hit_center - origin
            max_grid_dist = np.max(np.abs(delta / self.voxel_size))
            num_steps = int(np.ceil(max_grid_dist))
            if num_steps <= 0:
                continue
            t = (np.arange(num_steps, dtype=np.float32) /
                 float(num_steps))[:, None]
            samples = origin[None, :] + t * delta[None, :]
            voxels = self.coord_to_index_floor(samples)
            valid = np.all((voxels >= 0) & (voxels < self.occ_size), axis=1)
            voxels = voxels[valid]
            if voxels.shape[0] == 0:
                continue
            voxels = np.unique(voxels, axis=0)
            voxels = voxels[np.any(voxels != hit[None, :], axis=1)]
            if voxels.shape[0] > 0:
                free_chunks.append(voxels)
        if not free_chunks:
            return np.empty((0, 3), dtype=np.int64)
        return np.unique(np.concatenate(free_chunks, axis=0), axis=0)

    def ego_ignore_bev_mask(self) -> np.ndarray:
        mask = np.zeros((self.bev_h, self.bev_w), dtype=np.uint8)
        if self.ego_ignore_range is None:
            return mask
        lo = np.maximum(self.ego_ignore_range[:3], self.pc_range[:3])
        hi = np.minimum(self.ego_ignore_range[3:], self.pc_range[3:])
        if np.any(hi <= lo):
            return mask
        x_idx = np.arange(self.occ_size[0], dtype=np.int64)
        y_idx = np.arange(self.occ_size[1], dtype=np.int64)
        xs = self.voxel_centers(0, x_idx)
        ys = self.voxel_centers(1, y_idx)
        x_keep = np.flatnonzero((xs >= lo[0]) & (xs <= hi[0]))
        y_keep = np.flatnonzero((ys >= lo[1]) & (ys <= hi[1]))
        if x_keep.size == 0 or y_keep.size == 0:
            return mask
        rows = self.bev_h - 1 - y_keep
        mask[np.ix_(rows, x_keep)] = 1
        return mask

    def estimate_ground_height(self, points_xyz: np.ndarray,
                               point_voxels: np.ndarray):
        ground_raw = np.full(
            (self.occ_size[0], self.occ_size[1]), np.nan, dtype=np.float32)
        raw_ground_xy = np.zeros(
            (self.occ_size[0], self.occ_size[1]), dtype=bool)
        buckets = [[[] for _ in range(self.occ_size[1])]
                   for _ in range(self.occ_size[0])]
        for voxel, point in zip(point_voxels, points_xyz):
            buckets[int(voxel[0])][int(voxel[1])].append(float(point[2]))

        for i in range(self.occ_size[0]):
            for j in range(self.occ_size[1]):
                if buckets[i][j]:
                    raw_ground_xy[i, j] = True
                    ground_raw[i, j] = np.percentile(buckets[i][j], 10)

        ground_est = np.full_like(ground_raw, np.nan)
        radius = self.ground_smooth_radius
        for i in range(self.occ_size[0]):
            x0, x1 = max(0, i - radius), min(self.occ_size[0], i + radius + 1)
            for j in range(self.occ_size[1]):
                y0 = max(0, j - radius)
                y1 = min(self.occ_size[1], j + radius + 1)
                vals = ground_raw[x0:x1, y0:y1]
                vals = vals[np.isfinite(vals)]
                if vals.size:
                    ground_est[i, j] = np.percentile(vals, 25)
        return ground_est, raw_ground_xy

    def filter_obstacle_voxels(self, obstacle_voxels: np.ndarray,
                               scene_point_voxels: np.ndarray) -> np.ndarray:
        if obstacle_voxels.shape[0] == 0:
            return obstacle_voxels

        filtered = obstacle_voxels
        counts = None
        if (self.obstacle_min_points_per_voxel > 1 or
                self.obstacle_small_component_keep_min_points > 0 or
                self.obstacle_thin_component_keep_min_points > 0):
            counts = np.zeros(tuple(self.occ_size.tolist()), dtype=np.uint16)
            if scene_point_voxels.shape[0] > 0:
                np.add.at(counts, tuple(scene_point_voxels.T), 1)
        if self.obstacle_min_points_per_voxel > 1:
            keep = (
                counts[filtered[:, 0], filtered[:, 1], filtered[:, 2]] >=
                self.obstacle_min_points_per_voxel)
            filtered = filtered[keep]
            if filtered.shape[0] == 0:
                return filtered

        if (self.obstacle_min_component_voxels <= 1 and
                not self.filter_thin_obstacle_components):
            return filtered

        obstacle_mask = np.zeros(tuple(self.occ_size.tolist()), dtype=bool)
        obstacle_mask[filtered[:, 0], filtered[:, 1], filtered[:, 2]] = True
        visited = np.zeros_like(obstacle_mask)
        keep_mask = np.zeros_like(obstacle_mask)
        neighbors = (
            (1, 0, 0), (-1, 0, 0), (0, 1, 0),
            (0, -1, 0), (0, 0, 1), (0, 0, -1))

        for start in filtered:
            start_tuple = tuple(int(v) for v in start)
            if visited[start_tuple] or not obstacle_mask[start_tuple]:
                continue
            stack = [start_tuple]
            visited[start_tuple] = True
            component = []
            while stack:
                voxel = stack.pop()
                component.append(voxel)
                for offset in neighbors:
                    nxt = (
                        voxel[0] + offset[0],
                        voxel[1] + offset[1],
                        voxel[2] + offset[2])
                    if (0 <= nxt[0] < self.occ_size[0] and
                            0 <= nxt[1] < self.occ_size[1] and
                            0 <= nxt[2] < self.occ_size[2] and
                            obstacle_mask[nxt] and not visited[nxt]):
                        visited[nxt] = True
                        stack.append(nxt)
            if len(component) < self.obstacle_min_component_voxels:
                if not self.should_keep_dense_small_component(
                        component, counts):
                    continue
            if self.is_thin_obstacle_component(component, counts):
                continue
            for voxel in component:
                keep_mask[voxel] = True

        keep = keep_mask[filtered[:, 0], filtered[:, 1], filtered[:, 2]]
        return filtered[keep]

    def component_point_count(self, component: Sequence[Tuple[int, int, int]],
                              point_counts: Optional[np.ndarray]) -> int:
        if point_counts is None:
            return 0
        component_idx = np.asarray(component, dtype=np.int64)
        return int(point_counts[component_idx[:, 0], component_idx[:, 1],
                                component_idx[:, 2]].sum())

    def should_keep_dense_small_component(
            self,
            component: Sequence[Tuple[int, int, int]],
            point_counts: Optional[np.ndarray]) -> bool:
        return (
            self.obstacle_small_component_keep_min_points > 0 and
            self.component_point_count(component, point_counts) >=
            self.obstacle_small_component_keep_min_points)

    def is_thin_obstacle_component(
            self,
            component: Sequence[Tuple[int, int, int]],
            point_counts: Optional[np.ndarray] = None) -> bool:
        if not self.filter_thin_obstacle_components:
            return False
        component_idx = np.asarray(component, dtype=np.int64)
        if (self.obstacle_thin_component_keep_min_points > 0 and
                point_counts is not None):
            if (self.component_point_count(component_idx, point_counts) >=
                    self.obstacle_thin_component_keep_min_points):
                return False
        centers = self.pc_range[:3] + (
            component_idx.astype(np.float32) + 0.5) * self.voxel_size
        span = centers.max(axis=0) - centers.min(axis=0)
        major_xy_span = float(max(span[0], span[1]))
        minor_xy_span = float(min(span[0], span[1]))
        z_span = float(span[2])
        eps = 1e-4
        return (
            major_xy_span + eps >=
            self.obstacle_thin_component_min_major_span and
            minor_xy_span <=
            self.obstacle_thin_component_max_minor_span + eps and
            z_span <= self.obstacle_thin_component_max_z_span + eps)

    def obstacle_near_box_mask(self, obstacle_voxels: np.ndarray,
                               boxes: np.ndarray) -> np.ndarray:
        mask = np.zeros((obstacle_voxels.shape[0],), dtype=bool)
        if (obstacle_voxels.shape[0] == 0 or boxes.shape[0] == 0 or
                self.obstacle_box_ignore_margin <= 0):
            return mask
        margin = self.obstacle_box_ignore_margin
        centers = (
            self.pc_range[:3] +
            (obstacle_voxels.astype(np.float32) + 0.5) * self.voxel_size)
        for box_arr in boxes:
            length, width, height = box_arr[3:6]
            if length <= 0 or width <= 0 or height <= 0:
                continue
            yaw = box_arr[6]
            cos_yaw = np.cos(yaw)
            sin_yaw = np.sin(yaw)
            rel_x = centers[:, 0] - box_arr[0]
            rel_y = centers[:, 1] - box_arr[1]
            local_x = rel_x * cos_yaw + rel_y * sin_yaw
            local_y = -rel_x * sin_yaw + rel_y * cos_yaw
            inside = (
                (np.abs(local_x) <= length * 0.5 + margin) &
                (np.abs(local_y) <= width * 0.5 + margin) &
                (centers[:, 2] >= box_arr[2] - margin) &
                (centers[:, 2] <= box_arr[2] + height + margin))
            mask |= inside
        return mask

    def split_scene_ground_obstacle(
            self, scene_points_xyz: np.ndarray,
            scene_point_voxels: np.ndarray,
            scene_hit_voxels: np.ndarray,
            semantic_voxels: np.ndarray) -> Tuple[np.ndarray, np.ndarray,
                                                  np.ndarray]:
        if scene_hit_voxels.shape[0] == 0 or scene_points_xyz.shape[0] == 0:
            empty = np.empty((0, 3), dtype=np.int64)
            return empty, empty, empty

        ground_est, raw_ground_xy = self.estimate_ground_height(
            scene_points_xyz, scene_point_voxels)
        center_z = (self.pc_range[2] +
                    (scene_hit_voxels[:, 2].astype(np.float32) + 0.5) *
                    self.voxel_size[2])
        cell_ground = ground_est[scene_hit_voxels[:, 0],
                                 scene_hit_voxels[:, 1]]
        is_ground = (
            np.isfinite(cell_ground) &
            (center_z <= cell_ground + self.ground_height_threshold))
        observed_ground = scene_hit_voxels[is_ground]
        raw_obstacle = scene_hit_voxels[~is_ground]
        obstacle = self.filter_obstacle_voxels(
            raw_obstacle, scene_point_voxels)

        if self.fill_ground:
            fill_xy = np.zeros_like(raw_ground_xy)
            radius = self.ground_fill_radius
            for i in range(self.occ_size[0]):
                x0 = max(0, i - radius)
                x1 = min(self.occ_size[0], i + radius + 1)
                for j in range(self.occ_size[1]):
                    y0 = max(0, j - radius)
                    y1 = min(self.occ_size[1], j + radius + 1)
                    if (raw_ground_xy[x0:x1, y0:y1].sum() >=
                            self.ground_fill_min_neighbors and
                            np.isfinite(ground_est[i, j])):
                        fill_xy[i, j] = True
            xy = np.argwhere(fill_xy)
            z_idx = np.floor(
                (ground_est[fill_xy] - self.pc_range[2]) /
                self.voxel_size[2]).astype(np.int64)
            valid = (z_idx >= 0) & (z_idx < self.occ_size[2])
            ground = np.column_stack([xy[valid], z_idx[valid]])
        else:
            ground = observed_ground

        if self.remove_ground_under_obstacle and ground.shape[0] > 0:
            blocked_xy = set(map(tuple, obstacle[:, :2].tolist()))
            if semantic_voxels.shape[0] > 0:
                blocked_xy.update(map(tuple, semantic_voxels[:, :2].tolist()))
            keep = np.asarray(
                [tuple(voxel[:2]) not in blocked_xy for voxel in ground],
                dtype=bool)
            ground = ground[keep]
        return ground, obstacle, raw_obstacle

    def voxels_to_bev(self, voxels: np.ndarray) -> np.ndarray:
        mask = np.zeros((self.bev_h, self.bev_w), dtype=np.uint8)
        if voxels.shape[0] == 0:
            return mask
        rows = self.bev_h - 1 - voxels[:, 1]
        cols = voxels[:, 0]
        valid = (
            (rows >= 0) & (rows < self.bev_h) &
            (cols >= 0) & (cols < self.bev_w))
        mask[rows[valid], cols[valid]] = 1
        return mask

    def build(self, points: np.ndarray, boxes: np.ndarray) -> dict:
        pts = np.asarray(points[:, :3], dtype=np.float32)
        point_voxels = self.coord_to_index_floor(pts)
        valid = np.all((point_voxels >= 0) & (point_voxels < self.occ_size),
                       axis=1)
        pts = pts[valid]
        point_voxels = point_voxels[valid]
        if point_voxels.shape[0] == 0:
            empty = np.zeros((self.bev_h, self.bev_w), dtype=np.uint8)
            return dict(
                ground=empty,
                obstacle=empty,
                free=empty,
                blocked=empty,
                meta=dict(num_hit_voxels=0))

        hit_voxels = np.unique(point_voxels, axis=0)
        free_voxels = self.raycast_free_voxels(hit_voxels)
        box_mask = self.box_interior_mask(boxes)
        point_in_box = box_mask[
            point_voxels[:, 0], point_voxels[:, 1], point_voxels[:, 2]]
        scene_points = pts[~point_in_box]
        scene_point_voxels = point_voxels[~point_in_box]
        hit_in_box = box_mask[
            hit_voxels[:, 0], hit_voxels[:, 1], hit_voxels[:, 2]]
        scene_hit_voxels = hit_voxels[~hit_in_box]
        semantic_voxels = hit_voxels[hit_in_box]

        ground_voxels, obstacle_voxels, raw_obstacle_voxels = (
            self.split_scene_ground_obstacle(
                scene_points, scene_point_voxels, scene_hit_voxels,
                semantic_voxels))
        box_margin_obstacle_count = 0
        if obstacle_voxels.shape[0] > 0:
            near_box = self.obstacle_near_box_mask(obstacle_voxels, boxes)
            box_margin_obstacle_count = int(near_box.sum())
            obstacle_voxels = obstacle_voxels[~near_box]
            if obstacle_voxels.shape[0] > 0:
                obstacle_voxels = self.filter_obstacle_voxels(
                    obstacle_voxels, scene_point_voxels)

        ground_mask = self.voxels_to_bev(ground_voxels)
        obstacle_mask = self.voxels_to_bev(obstacle_voxels)
        semantic_mask = self.voxels_to_bev(semantic_voxels)
        free_mask = self.voxels_to_bev(free_voxels)
        blocked_mask = np.maximum(obstacle_mask, semantic_mask).astype(np.uint8)
        ego_ignore_mask = self.ego_ignore_bev_mask()
        if ego_ignore_mask.any():
            ground_mask[ego_ignore_mask > 0] = 0
            obstacle_mask[ego_ignore_mask > 0] = 0
            free_mask[ego_ignore_mask > 0] = 0
            blocked_mask[ego_ignore_mask > 0] = 0

        return dict(
            ground=ground_mask,
            obstacle=obstacle_mask,
            free=free_mask,
            blocked=blocked_mask,
            meta=dict(
                num_points=int(pts.shape[0]),
                num_hit_voxels=int(hit_voxels.shape[0]),
                num_free_voxels=int(free_voxels.shape[0]),
                num_scene_hit_voxels=int(scene_hit_voxels.shape[0]),
                num_ground_voxels=int(ground_voxels.shape[0]),
                num_raw_obstacle_voxels=int(raw_obstacle_voxels.shape[0]),
                num_obstacle_voxels=int(obstacle_voxels.shape[0]),
                num_semantic_voxels=int(semantic_voxels.shape[0]),
                num_box_margin_obstacle_voxels=box_margin_obstacle_count))


def build_target(drivable_global, info: dict, points: np.ndarray,
                 boxes: np.ndarray, pc_range: Sequence[float],
                 bev_size: Sequence[int],
                 args: argparse.Namespace) -> DrivableTarget:
    map_mask = build_map_mask(drivable_global, info, pc_range, bev_size)
    if args.augment_raycast_ground:
        raycast = RaycastDrivableBuilder(pc_range, bev_size, args).build(
            points, boxes)
        ground_mask = raycast['ground']
        obstacle_mask = raycast['blocked']
        fused_mask = np.maximum(map_mask, ground_mask).astype(np.uint8)
        if not args.keep_raycast_obstacles:
            fused_mask[obstacle_mask > 0] = 0
        free_mask = raycast['free']
        augmentation = 'raycast'
    elif args.augment_lidar_ground:
        ground_mask, obstacle_mask = lidar_ground_masks(
            points, boxes, pc_range, bev_size, args)
        fused_mask = np.maximum(map_mask, ground_mask).astype(np.uint8)
        free_mask = None
        augmentation = 'lidar_ground'
    else:
        ground_mask = None
        obstacle_mask = None
        fused_mask = map_mask
        free_mask = None
        augmentation = 'map'
    target = target_from_mask(fused_mask)
    target.map_mask = map_mask
    target.lidar_ground_mask = ground_mask
    target.lidar_obstacle_mask = obstacle_mask
    target.raycast_free_mask = free_mask
    target.augmentation = augmentation
    return target


def resolve_start_index(infos: Sequence[dict], args: argparse.Namespace) -> int:
    if args.token is None and args.scene_token is None:
        if args.start_index < 0 or args.start_index >= len(infos):
            raise IndexError(f'--start-index {args.start_index} out of range')
        return args.start_index
    for idx, info in enumerate(infos):
        if args.token is not None and info.get('token') == args.token:
            return idx
        if args.scene_token is not None and (
                info.get('scene_token') == args.scene_token):
            return idx
    key = args.token if args.token is not None else args.scene_token
    raise KeyError(f'Cannot find requested token/scene: {key}')


def selected_indices(infos: Sequence[dict], args: argparse.Namespace) -> List[int]:
    if args.indices:
        out = []
        for idx in args.indices:
            if idx < 0 or idx >= len(infos):
                raise IndexError(f'index {idx} out of range 0..{len(infos)-1}')
            out.append(int(idx))
        return out
    start = resolve_start_index(infos, args)
    scene_token = infos[start].get('scene_token')
    out = []
    for idx in range(start, len(infos)):
        if args.scene_token is not None and infos[idx].get(
                'scene_token') != scene_token:
            break
        out.append(idx)
        if len(out) >= args.max_samples:
            break
    return out


def resolve_lidar_path(info: dict, data_root: str, pts_prefix: str) -> str:
    lidar_info = info.get('lidar_points', {})
    lidar_path = lidar_info.get('lidar_path', info.get('lidar_path'))
    if lidar_path is None:
        raise KeyError('info does not contain a LiDAR path')
    if osp.isabs(lidar_path) or osp.exists(lidar_path):
        return lidar_path
    return osp.join(data_root, pts_prefix, lidar_path)


def load_points(info: dict, data_root: str, pts_prefix: str) -> np.ndarray:
    path = resolve_lidar_path(info, data_root, pts_prefix)
    num_feats = int(info.get('lidar_points', {}).get(
        'num_pts_feats', info.get('num_features', 4)))
    points = np.fromfile(path, dtype=np.float32)
    return points.reshape(-1, num_feats)


def map_label(label: int, label_mapping: Sequence[int],
              num_classes: int) -> int:
    label = int(label)
    if label < 0 or label >= len(label_mapping):
        return -1
    label = int(label_mapping[label])
    if label < 0 or label >= num_classes:
        return -1
    return label


def gt_arrays_from_info(info: dict) -> Tuple[np.ndarray, np.ndarray]:
    boxes = []
    labels = []
    for inst in info.get('instances', []):
        label = map_label(
            inst.get('bbox_label_3d', inst.get('bbox_label', -1)),
            DEFAULT_LABEL_MAPPING,
            len(DEFAULT_CLASS_NAMES))
        if label < 0:
            continue
        if not bool(inst.get('bbox_3d_isvalid', True)):
            continue
        if int(inst.get('num_lidar_pts', 1)) <= 0:
            continue
        box_arr = np.asarray(inst['bbox_3d'], dtype=np.float32)
        if box_arr.shape[0] < 9:
            vel = np.asarray(inst.get('velocity', [0.0, 0.0]),
                             dtype=np.float32)
            if box_arr.shape[0] == 7:
                box_arr = np.concatenate([box_arr, vel[:2]])
            else:
                box_arr = np.pad(box_arr, (0, 9 - box_arr.shape[0]))
        boxes.append(box_arr[:9])
        labels.append(label)
    if not boxes:
        return (np.zeros((0, 9), dtype=np.float32),
                np.zeros((0,), dtype=np.int64))
    return np.asarray(boxes, dtype=np.float32), np.asarray(labels, dtype=np.int64)


def compute_box_corners_bev(boxes: np.ndarray) -> np.ndarray:
    if boxes.size == 0:
        return np.zeros((0, 4, 2), dtype=np.float32)
    corners = []
    for box_arr in boxes:
        x, y, _, length, width, _, yaw = box_arr[:7]
        c = math.cos(float(yaw))
        s = math.sin(float(yaw))
        rot = np.asarray([[c, -s], [s, c]], dtype=np.float32)
        local = np.asarray([
            [length / 2, width / 2],
            [length / 2, -width / 2],
            [-length / 2, -width / 2],
            [-length / 2, width / 2],
        ], dtype=np.float32)
        corners.append(local @ rot.T + np.asarray([x, y], dtype=np.float32))
    return np.stack(corners, axis=0)


def lidar_xy_to_display(xy: np.ndarray) -> np.ndarray:
    disp = np.empty_like(xy, dtype=np.float32)
    disp[..., 0] = -xy[..., 1]
    disp[..., 1] = xy[..., 0]
    return disp


def setup_axis(ax, pc_range: Sequence[float], title: str) -> None:
    x_min, y_min, _, x_max, y_max, _ = [float(v) for v in pc_range]
    ax.set_facecolor('black')
    ax.set_xlim(-y_max, -y_min)
    ax.set_ylim(x_min, x_max)
    ax.set_aspect('equal', adjustable='box')
    ax.set_xlabel('Lateral (m)', color='white')
    ax.set_ylabel('Forward (m)', color='white')
    ax.tick_params(colors='white', labelsize=8)
    for spine in ax.spines.values():
        spine.set_color('#888888')
    ax.grid(color='#444444', linestyle='--', linewidth=0.5, alpha=0.35)
    ax.set_title(title, color='white', fontsize=10)


def draw_mask(ax, mask: np.ndarray, pc_range: Sequence[float],
              alpha: float) -> None:
    x_min, y_min, _, x_max, y_max, _ = [float(v) for v in pc_range]
    masked = np.ma.masked_where(mask <= 0, mask)
    ax.imshow(
        masked.T,
        extent=(-y_max, -y_min, x_min, x_max),
        origin='lower',
        cmap='Greens',
        interpolation='nearest',
        alpha=alpha)


def draw_colored_mask(ax, mask: np.ndarray, pc_range: Sequence[float],
                      color: Sequence[float], alpha: float) -> None:
    if mask is None or mask.sum() == 0:
        return
    x_min, y_min, _, x_max, y_max, _ = [float(v) for v in pc_range]
    rgba = np.zeros(mask.shape + (4,), dtype=np.float32)
    rgba[..., 0] = float(color[0])
    rgba[..., 1] = float(color[1])
    rgba[..., 2] = float(color[2])
    rgba[..., 3] = (mask > 0).astype(np.float32) * float(alpha)
    ax.imshow(
        rgba.transpose(1, 0, 2),
        extent=(-y_max, -y_min, x_min, x_max),
        origin='lower',
        interpolation='nearest')


def draw_points(ax, points: np.ndarray, point_stride: int) -> None:
    pts = points[::point_stride, :3]
    if len(pts) == 0:
        return
    disp = lidar_xy_to_display(pts[:, :2])
    ax.scatter(
        disp[:, 0],
        disp[:, 1],
        s=0.12,
        c='white',
        alpha=0.30,
        linewidths=0)


def draw_boxes(ax, boxes: np.ndarray, labels: np.ndarray) -> None:
    corners = compute_box_corners_bev(boxes)
    for idx, poly in enumerate(corners):
        disp = lidar_xy_to_display(poly)
        closed = np.concatenate([disp, disp[:1]], axis=0)
        ax.plot(closed[:, 0], closed[:, 1], color='#00e5ff',
                linewidth=1.0, alpha=0.92)
        center = lidar_xy_to_display(boxes[idx:idx + 1, :2])[0]
        label = int(labels[idx]) if idx < len(labels) else -1
        name = DEFAULT_CLASS_NAMES[label] if 0 <= label < len(
            DEFAULT_CLASS_NAMES) else str(label)
        ax.text(
            center[0],
            center[1],
            name,
            color='#9beafe',
            fontsize=5.5,
            ha='left',
            va='bottom',
            alpha=0.85)


def draw_ego(ax) -> None:
    ax.plot(0.0, 0.0, marker='o', markersize=4, color='#ffd166')
    ax.arrow(
        0.0,
        0.0,
        0.0,
        3.0,
        color='#ffd166',
        width=0.03,
        head_width=0.5,
        head_length=0.6,
        length_includes_head=True)


def render_frame(points: np.ndarray, boxes: np.ndarray, labels: np.ndarray,
                 target: DrivableTarget, pc_range: Sequence[float],
                 save_path: str, title: str, point_stride: int,
                 mask_alpha: float) -> None:
    num_axes = 3 if target.lidar_ground_mask is not None else 2
    fig, axes = plt.subplots(1, num_axes, figsize=(5.6 * num_axes, 8.8),
                             dpi=160)
    fig.patch.set_facecolor('black')
    axes = np.atleast_1d(axes)
    left_ax = axes[0]
    map_ax = axes[1]
    fused_ax = axes[2] if num_axes == 3 else axes[1]
    map_mask = target.map_mask if target.map_mask is not None else target.mask
    map_coverage = float(map_mask.mean())
    fused_coverage = float(target.mask.mean())

    setup_axis(left_ax, pc_range, f'Point cloud + GT boxes ({len(boxes)})')
    setup_axis(map_ax, pc_range,
               f'HD map drivable | coverage={map_coverage:.3f}')
    draw_points(left_ax, points, point_stride)
    draw_boxes(left_ax, boxes, labels)
    draw_ego(left_ax)

    draw_mask(map_ax, map_mask, pc_range, mask_alpha)
    draw_points(map_ax, points, point_stride)
    draw_boxes(map_ax, boxes, labels)
    draw_ego(map_ax)

    if target.lidar_ground_mask is not None:
        ground_coverage = float(target.lidar_ground_mask.mean())
        setup_axis(fused_ax, pc_range,
                   f'Fused drivable ({target.augmentation}) | '
                   f'ground={ground_coverage:.3f} fused={fused_coverage:.3f}')
        if target.raycast_free_mask is not None:
            free_only = np.logical_and(target.raycast_free_mask > 0,
                                       target.mask == 0).astype(np.uint8)
            draw_colored_mask(fused_ax, free_only, pc_range,
                              color=(0.12, 0.45, 1.0), alpha=0.12)
        draw_colored_mask(fused_ax, map_mask, pc_range,
                          color=(0.22, 0.82, 0.30), alpha=mask_alpha)
        ground_only = np.logical_and(target.lidar_ground_mask > 0,
                                     map_mask == 0).astype(np.uint8)
        draw_colored_mask(fused_ax, ground_only, pc_range,
                          color=(0.95, 0.72, 0.18),
                          alpha=min(mask_alpha + 0.18, 0.8))
        if target.lidar_obstacle_mask is not None:
            draw_colored_mask(fused_ax, target.lidar_obstacle_mask, pc_range,
                              color=(0.98, 0.16, 0.12), alpha=0.28)
        draw_points(fused_ax, points, point_stride)
        draw_boxes(fused_ax, boxes, labels)
        draw_ego(fused_ax)

    fig.suptitle(title, color='white', fontsize=11)
    fig.subplots_adjust(
        left=0.055, right=0.985, bottom=0.07, top=0.91, wspace=0.08)
    fig.savefig(save_path, facecolor=fig.get_facecolor())
    plt.close(fig)


def write_html(out_dir: str, html_name: str, frame_files: Sequence[str]) -> None:
    if not frame_files:
        return
    frames = [osp.basename(path) for path in frame_files]
    buttons = '\n'.join(
        f'<button onclick="show({idx})">{idx}</button>'
        for idx in range(len(frames)))
    js_frames = json.dumps(frames)
    html = f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>KL drivable GT</title>
  <style>
    body {{ margin: 0; background: #080808; color: #eee; font-family: sans-serif; }}
    #bar {{ position: sticky; top: 0; padding: 8px; background: #111; }}
    button {{ margin: 2px; }}
    img {{ display: block; max-width: 100vw; margin: 0 auto; }}
  </style>
</head>
<body>
  <div id="bar">
    <button onclick="prev()">prev</button>
    <button onclick="next()">next</button>
    <span id="label"></span>
    <div>{buttons}</div>
  </div>
  <img id="frame" />
  <script>
    const frames = {js_frames};
    let idx = 0;
    function show(i) {{
      idx = (i + frames.length) % frames.length;
      document.getElementById('frame').src = frames[idx];
      document.getElementById('label').textContent = `${{idx + 1}}/${{frames.length}} ${{frames[idx]}}`;
    }}
    function next() {{ show(idx + 1); }}
    function prev() {{ show(idx - 1); }}
    document.addEventListener('keydown', e => {{
      if (e.key === 'ArrowRight') next();
      if (e.key === 'ArrowLeft') prev();
    }});
    show(0);
  </script>
</body>
</html>
"""
    with open(osp.join(out_dir, html_name), 'w') as f:
        f.write(html)


def main() -> None:
    args = parse_args()
    os.makedirs(args.out_dir, exist_ok=True)

    print(f'Loading infos: {args.ann_file}')
    infos = load_infos(args.ann_file)
    if args.clean_map_file and osp.exists(args.clean_map_file):
        print(f'Loading clean map: {args.clean_map_file}')
        drivable_global = load_clean_drivable_geometry(args.clean_map_file)
        stats = MapStats(drivable_area=float(drivable_global.area))
    else:
        print(f'Parsing map: {args.map_file}')
        drivable_global, stats = build_drivable_geometry(args)
    stats_path = osp.join(args.out_dir, 'map_summary.json')
    with open(stats_path, 'w') as f:
        json.dump(stats.__dict__, f, indent=2)
    print(f'Map summary written to {stats_path}')
    print(json.dumps(stats.__dict__, indent=2))

    frame_files = []
    for index in selected_indices(infos, args):
        info = infos[index]
        points = load_points(info, args.data_root, args.pts_prefix)
        boxes, labels = gt_arrays_from_info(info)
        target = build_target(drivable_global, info, points, boxes,
                              args.pc_range, args.bev_size, args)
        stem = f'{index:06d}_{info.get("token", "")[:8]}'
        png_path = osp.join(args.out_dir, f'{stem}_drivable_gt.png')
        title = (
            f'KL drivable GT | index={index} token={info.get("token", "")}\n'
            f'scene={info.get("scene_token", "")}')
        render_frame(
            points=points,
            boxes=boxes,
            labels=labels,
            target=target,
            pc_range=args.pc_range,
            save_path=png_path,
            title=title,
            point_stride=args.point_stride,
            mask_alpha=args.mask_alpha)
        frame_files.append(png_path)

        if args.save_npz:
            np.savez_compressed(
                osp.join(args.out_dir, f'{stem}_drivable_gt.npz'),
                mask=target.mask,
                gt_lane_labels=target.gt_lane_labels,
                gt_lane_bboxes=target.gt_lane_bboxes,
                gt_lane_masks=target.gt_lane_masks,
                map_mask=target.map_mask,
                lidar_ground_mask=target.lidar_ground_mask,
                lidar_obstacle_mask=target.lidar_obstacle_mask,
                raycast_free_mask=target.raycast_free_mask,
                augmentation=target.augmentation,
                token=info.get('token', ''),
                scene_token=info.get('scene_token', ''),
                ego2global=np.asarray(info.get('ego2global', np.eye(4))))
        print(
            f'Wrote {png_path} | mask_pixels={int(target.mask.sum())} '
            f'coverage={float(target.mask.mean()):.4f} '
            f'augmentation={target.augmentation} '
            f'map_coverage={float(target.map_mask.mean()):.4f} '
            f'lidar_coverage='
            f'{float(target.lidar_ground_mask.mean()) if target.lidar_ground_mask is not None else 0.0:.4f} '
            f'obstacle_coverage='
            f'{float(target.lidar_obstacle_mask.mean()) if target.lidar_obstacle_mask is not None else 0.0:.4f} '
            f'free_coverage='
            f'{float(target.raycast_free_mask.mean()) if target.raycast_free_mask is not None else 0.0:.4f}')

    write_html(args.out_dir, args.html_name, frame_files)
    print(f'HTML viewer: {osp.join(args.out_dir, args.html_name)}')


if __name__ == '__main__':
    main()
